#!/usr/bin/env python3
"""Pack rendered frames into a flipbook atlas, and AUDIT it before it ships.

    python3 scripts/flipbook/pack.py build_cache/smoke_puff/frames --grid 8 \
        --alpha-from-luma 0 --split --shape puff --out smoke_puff_8x8.png
    python3 scripts/flipbook/pack.py assets/textures/smoke_puff_8x8.png --grid 8

A separate stage because a re-pack (different normalisation, a different grid,
a re-audit of something that already shipped) costs seconds instead of a re-sim.

THE AUDIT IS THE POINT. E4's first fire sheet reached the engine and only THEN
was measured at 4.1% coverage and height/width 1.00 — a spherical puff. What is
checked here: framing (reach / clipped — the thing a screenshot cannot judge
once it saturates), silhouette (lobes), shape (height/width, for columns), and
the per-channel split. There is deliberately no coverage TARGET; see README.
"""

import argparse
import glob
import math
import os
import sys

import numpy as np
from PIL import Image

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "assets", "textures")


def frame_crop_metadata(sheet, grid, cell):
    """Return conservative occupied bounds in each cell's local UV space.

    This is deliberately derived from alpha, not the flame R channel: packed
    volume sheets need to retain the dim soot contour as well as the hot core.
    The small adaptive threshold avoids making a late, nearly-empty frame grow
    back to a full card because of a handful of filtered pixels.
    """
    alpha = np.asarray(sheet)[..., 3]
    crops = []
    pad = max(2, int(round(cell * 0.02)))
    for f in range(grid * grid):
        r, c = divmod(f, grid)
        sub = alpha[r * cell:(r + 1) * cell, c * cell:(c + 1) * cell]
        peak = int(sub.max())
        mask = sub >= max(15, int(round(peak * 0.08)))
        if peak == 0 or not mask.any():
            crops.append((0.0, 0.0, 1.0, 1.0))
            continue
        ys, xs = np.nonzero(mask)
        x0 = max(0, int(xs.min()) - pad)
        y0 = max(0, int(ys.min()) - pad)
        x1 = min(cell, int(xs.max()) + 1 + pad)
        y1 = min(cell, int(ys.max()) + 1 + pad)
        crops.append((x0 / cell, y0 / cell, (x1 - x0) / cell, (y1 - y0) / cell))
    return crops


def write_frame_metadata(path, symbol, crops):
    """Emit a C include consumed by SpriteAnim_SetFrameMetadata()."""
    lines = [
        "/* Generated by scripts/flipbook/pack.py --meta-out. Do not hand-edit. */",
        "static const SpriteAnimFrameMeta %s[%d] = {" % (symbol, len(crops)),
    ]
    for x, y, w, h in crops:
        lines.append("    {.crop = {%.6ff, %.6ff, %.6ff, %.6ff}}," % (x, y, w, h))
    lines.append("};")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def audit(sheet, grid, cell):
    arr = np.asarray(sheet).astype(np.float32) / 255.0
    a = arr[..., 3]
    covs, ratios, rough = [], [], []
    reach = 0.0          # farthest lit pixel, as a fraction of the cell HALF-width
    clipped = 0
    half = cell / 2.0
    for f in range(grid * grid):
        r, c = divmod(f, grid)
        sub = a[r * cell:(r + 1) * cell, c * cell:(c + 1) * cell]
        m = sub > 0.06
        if m.sum() < 32:
            continue
        covs.append(m.mean())
        ys, xs = np.nonzero(m)
        ratios.append((ys.max() - ys.min() + 1) / max(1, (xs.max() - xs.min() + 1)))
        # FRAMING, measured instead of eyeballed. A sheet is clipped the moment a
        # lit pixel lands on the cell border, and a screenshot cannot tell that
        # apart from a puff that merely fills the frame. reach > 1 is impossible
        # (the crop stops there), so a value AT 1.0 with border pixels lit means
        # the effect was cut, not framed.
        d = max(abs(ys.max() + 0.5 - half), abs(ys.min() + 0.5 - half),
                abs(xs.max() + 0.5 - half), abs(xs.min() + 0.5 - half)) / half
        reach = max(reach, d)
        if (m[0].any() or m[-1].any() or m[:, 0].any() or m[:, -1].any()):
            clipped += 1
        # LOBE COUNT, as an isoperimetric ratio: perimeter / (2*sqrt(pi*area)).
        # 1.0 is a disc; cauliflower is many small convex billows, so the number
        # rises with lobe COUNT and is independent of the puff's size on screen —
        # which is what makes it comparable across resolutions and zooms.
        mm = sub > 0.35
        area = int(mm.sum())
        if area > 64:
            edge = mm & ~(np.roll(mm, 1, 0) & np.roll(mm, -1, 0)
                          & np.roll(mm, 1, 1) & np.roll(mm, -1, 1))
            rough.append(int(edge.sum()) / (2.0 * math.sqrt(math.pi * area)))
    # Channel coverage, reported separately: on a two-population sheet the alpha
    # figure is the UNION of flame and smoke, so it says nothing about either.
    flame_cov = float((arr[..., 0] > 0.25).mean())
    smoke_cov = float((arr[..., 1] > 0.25).mean())
    return (float(np.mean(covs)) if covs else 0.0,
            float(np.mean(ratios)) if ratios else 0.0,
            len(covs), flame_cov, smoke_cov,
            reach, clipped, float(np.mean(rough)) if rough else 0.0)


def temporal_audit(sheet, grid, cell):
    """Measure the flame channel the runtime actually maps through its ramp.

    A flipbook may have a soft alpha edge yet still read as stamped white discs
    when R barely changes or spends too much of its lit area near 1.0. These
    two metrics catch that exact failure before a sheet reaches an emitter.

    Brightness is not shape: a puff can cool, change every R value, and still
    retain exactly the same gas silhouette.  The final value therefore compares
    adjacent, individually normalised R masks.  It is the fraction of their
    union that changed (one minus IoU), so a global fade cannot inflate it.
    """
    arr = np.asarray(sheet).astype(np.float32) / 255.0
    frames = []
    for f in range(grid * grid):
        r, c = divmod(f, grid)
        frames.append(arr[r * cell:(r + 1) * cell,
                          c * cell:(c + 1) * cell, 0])
    frames = np.asarray(frames)
    hot = frames > 0.02
    if not hot.any():
        return 0.0, 0.0, 1.0, 0.0, 0.0
    plateau = float((frames[hot] > 0.75).mean())
    transition = float(((frames[hot] > 0.02) & (frames[hot] < 0.75)).sum()
                       / hot.sum())
    deltas = []
    for i in range(len(frames) - 1):
        mean = 0.5 * (float(frames[i].mean()) + float(frames[i + 1].mean()))
        if mean > 1e-5:
            deltas.append(float(np.abs(frames[i] - frames[i + 1]).mean()) / mean)
    # The late event is the important one for a particle flipbook: a burst can
    # change dramatically at ignition then coast as a frozen card for 75% of
    # the sheet. Report frames 16..64 separately so that exact failure cannot
    # be hidden by a lively first few cells.
    late_start = max(0, len(frames) // 4)
    late = []
    late_shape = []
    # A 64-cell atlas is normally played at 24–60 FPS.  Requiring a 10% mask
    # change in *each adjacent cell* rewards popping, not fluid motion.  The
    # quality question is whether a viewer can still see the gas advance over
    # a short readable interval, so inspect an eighth of a second-ish window
    # (8 cells) as well as the adjacent-frame smoothness diagnostic.
    lookahead = max(2, len(frames) // 8)
    late_advance = []
    for i in range(late_start, len(frames) - 1):
        mean = 0.5 * (float(frames[i].mean()) + float(frames[i + 1].mean()))
        if mean > 1e-5:
            late.append(float(np.abs(frames[i] - frames[i + 1]).mean()) / mean)
        # Normalise each frame separately.  If frame k is merely a dimmer copy
        # of frame k+1, these masks are identical and the result is zero.
        peak = max(float(frames[i].max()), float(frames[i + 1].max()))
        if peak > 1e-5:
            a = frames[i] > peak * 0.18
            b = frames[i + 1] > peak * 0.18
            union = int((a | b).sum())
            if union:
                late_shape.append(1.0 - float((a & b).sum()) / union)
        if i + lookahead < len(frames):
            peak = max(float(frames[i].max()), float(frames[i + lookahead].max()))
            if peak > 1e-5:
                a = frames[i] > peak * 0.18
                b = frames[i + lookahead] > peak * 0.18
                union = int((a | b).sum())
                if union:
                    late_advance.append(1.0 - float((a & b).sum()) / union)
    return (plateau, transition, float(np.mean(deltas)) if deltas else 0.0,
            float(np.mean(late)) if late else 0.0,
            float(np.mean(late_shape)) if late_shape else 0.0,
            float(np.mean(late_advance)) if late_advance else 0.0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("frames_dir",
                    help="folder of rendered frames, or an existing SHEET .png "
                         "to re-audit in place (a sheet that shipped before a "
                         "measurement existed has never been held to it)")
    ap.add_argument("--grid", type=int, default=8)
    ap.add_argument("--out", default="flipbook_8x8.png")
    ap.add_argument("--cell", type=int, default=None)
    ap.add_argument("--stride", type=int, default=1,
                    help="take every Nth rendered frame. A smaller GRID must not "
                         "be produced by simulating fewer frames: --frames is a "
                         "PHYSICS axis (dt is per frame), so a 16-frame sim is an "
                         "earlier MOMENT of the effect, not a coarser sampling of "
                         "it. Simulate the full event, then subsample here.")
    ap.add_argument("--offset", type=int, default=0,
                    help="skip this many rendered frames before subsampling. Use it "
                         "when f000 is an ignition seed rather than a drawable frame.")
    ap.add_argument("--hold-after", type=int, default=0,
                    help="use the first N sampled frames, then repeat frame N for "
                         "the remaining atlas cells. For dust this prevents a solver "
                         "dissipation tail from visibly shrinking the parcel; runtime "
                         "alpha owns the fade.")
    ap.add_argument("--split", action="store_true",
                    help="also write <out>_flame.png and <out>_smoke.png. The "
                         "engine's particle shader multiplies the WHOLE rgb by "
                         "the vertex colour, so a two-channel sheet used directly "
                         "would tint the flame with its own smoke. The FLAME "
                         "sheet is white RGB + alpha (it emits; its colour comes "
                         "from the ramp at the call site); the SMOKE sheet gets "
                         "the self-shadow (B/G) as its RGB value, because an "
                         "unshaded mask stacks into flat cards.")
    ap.add_argument("--shape", default="column", choices=["column", "puff"],
                    help="what the sheet is SUPPOSED to be. height/width > 1.3 is "
                         "a defect check for a rising column and nonsense for a "
                         "puff, which is round by definition — a warning that "
                         "fires on a correct sheet gets everything else ignored "
                         "with it.")
    ap.add_argument("--alpha-from-luma", type=float, default=1.0,
                    help="fold RGB luminance into alpha (1 = on). Emission-only "
                         "volumes render bright but nearly TRANSPARENT: Eevee's "
                         "alpha comes from extinction, not from emission, so a "
                         "flame measures rgb 255 / alpha 10. An additive flipbook "
                         "uses alpha as its MASK, so luminance is the right "
                         "source for it.")
    ap.add_argument("--meta-out", default=None,
                    help="optional C .inl path for per-frame occupied bounds. "
                         "The runtime uses it to crop transparent fill-rate while "
                         "preserving each frame's original pivot.")
    ap.add_argument("--meta-symbol", default="s_flipbookFrameMeta",
                    help="C symbol written by --meta-out")
    args = ap.parse_args()

    if args.frames_dir.lower().endswith(".png") and os.path.isfile(args.frames_dir):
        sheet = Image.open(args.frames_dir).convert("RGBA")
        cell = sheet.size[0] // args.grid
        if args.meta_out:
            write_frame_metadata(args.meta_out, args.meta_symbol,
                                 frame_crop_metadata(sheet, args.grid, cell))
            print("  frame metadata -> %s" % args.meta_out)
        report(audit(sheet, args.grid, cell), args, args.frames_dir, sheet)
        return 0

    files = sorted(glob.glob(os.path.join(args.frames_dir, "*.png")))
    if args.offset < 0:
        print("--offset must be >= 0")
        return 1
    files = files[args.offset:]
    if args.stride > 1:
        files = files[::args.stride]
    want = args.grid * args.grid
    if args.hold_after < 0 or args.hold_after > want:
        print("--hold-after must be in 0..%d" % want)
        return 1
    if len(files) < want:
        print("only %d frames in %s, need %d" % (len(files), args.frames_dir, want))
        return 1
    if args.hold_after:
        if len(files) < args.hold_after:
            print("only %d frames in %s, need %d before --hold-after" %
                  (len(files), args.frames_dir, args.hold_after))
            return 1
        files = files[:args.hold_after] + [files[args.hold_after - 1]] * (want - args.hold_after)
    else:
        files = files[:want]

    first = Image.open(files[0]).convert("RGBA")
    cell = args.cell or first.size[0]
    sheet = Image.new("RGBA", (args.grid * cell, args.grid * cell), (0, 0, 0, 0))
    for i, p in enumerate(files):
        im = Image.open(p).convert("RGBA")
        if im.size != (cell, cell):
            im = im.resize((cell, cell), Image.LANCZOS)
        if args.alpha_from_luma > 0.0:
            arr = np.asarray(im).astype(np.float32)
            luma = (0.299 * arr[..., 0] + 0.587 * arr[..., 1] + 0.114 * arr[..., 2])
            arr[..., 3] = np.clip(np.maximum(arr[..., 3], luma * args.alpha_from_luma), 0, 255)
            im = Image.fromarray(arr.astype(np.uint8), "RGBA")
        r, c = divmod(i, args.grid)
        sheet.paste(im, (c * cell, r * cell))

    path = os.path.join(OUT_DIR, args.out)
    sheet.save(path)

    if args.meta_out:
        write_frame_metadata(args.meta_out, args.meta_symbol,
                             frame_crop_metadata(sheet, args.grid, cell))
        print("  frame metadata -> %s" % args.meta_out)

    if args.split:
        a = np.asarray(sheet).astype(np.float32)
        base = os.path.splitext(args.out)[0]
        for chan, name in ((0, "flame"), (1, "smoke")):
            m = a[..., chan]
            if float((m > 64.0).mean()) < 0.01:
                # A cold effect has no usable flame channel — dust injects a
                # little heat that cools within a few frames, so the channel is
                # not literally empty, just spurious. Writing it anyway puts a
                # file in assets/ that looks like an asset and is not one.
                # Threshold matches the audit's own channel-coverage test.
                print("  split -> %s_%s SKIPPED (channel is empty)"
                      % (os.path.splitext(args.out)[0], name))
                continue
            out = np.zeros(a.shape, np.uint8)
            out[..., 0] = out[..., 1] = out[..., 2] = 255      # white: tint at
            out[..., 3] = np.clip(m, 0, 255).astype(np.uint8)  # the call site
            if chan == 1 and a[..., 2].max() > 0.5:
                # B holds the SAME integral with the light's transmittance folded
                # in, so B/G is the fraction of light that survived to this pixel
                # — pure shading, with the density falloff divided back out. That
                # is what belongs in RGB: the value. Multiplying the density in
                # twice (once in RGB, once in alpha) is what darkens a thick puff
                # into a silhouette.
                #
                # A FLAME sheet never gets this: it emits, so it is not shadowed
                # by anything, and its colour comes from the black-body ramp at
                # the call site.
                lit = np.maximum(m, 1e-3)
                val = np.clip(a[..., 2] / lit, 0.0, 1.0) * 255.0
                out[..., 0] = out[..., 1] = out[..., 2] = val.astype(np.uint8)
            p2 = os.path.join(OUT_DIR, "%s_%s.png" % (base, name))
            Image.fromarray(out, "RGBA").save(p2)
            print("  split -> %s  (mean alpha %.1f)" % (os.path.basename(p2), m.mean()))
    report(audit(sheet, args.grid, cell), args, path, sheet, want)
    return 0


def report(nums, args, path, sheet, want=None):
    cov, ratio, live, fcov, scov, reach, clipped, rough = nums
    if want is None:
        want = live
    print("%s  %dx%d  (%d non-empty frames)" % (path, sheet.size[0], sheet.size[1], live))
    # No "target" coverage is quoted any more. The 19.6% figure printed here for
    # a long time came from smoke_atlas_8x8.png, called the sheet that works —
    # the owner has since rejected that sheet, so every number calibrated
    # against it was calibrated against nothing. Coverage is reported; what it
    # should be is a judgement about the effect, not a constant.
    print("  cell coverage %.1f%%" % (cov * 100))
    print("  height/width  %.2f    (must exceed 1.30 — flame, not puff)" % ratio)
    print("  reach %.2f of the half-cell, %d/%d frames touch the border" % (reach, clipped, live))
    print("  lobes %.2f  (isoperimetric: 1.0 = one round blob, higher = more billows)" % rough)
    if reach > 0.001:
        # Framing scales linearly about the cell centre, so the corrected zoom is
        # exact arithmetic, not another guess-and-render round.
        print("  -> multiply render.py --zoom by %.2f to sit 2%% inside the border"
              % (0.98 / reach))
    if fcov > 0.001 or scov > 0.001:
        print("  channels: flame %.1f%% of sheet, smoke %.1f%% "
              "(R and G are separate populations — see render.py)"
              % (fcov * 100, scov * 100))
    plateau, transition, temporal, late_temporal, late_shape, late_advance = temporal_audit(
        sheet, args.grid, sheet.size[0] // args.grid)
    if fcov > 0.001:
        print("  flame R: plateau %.1f%%, transition %.1f%%, adjacent change %.1f%% "
              "(late frames 16..64 %.1f%%)"
              % (plateau * 100, transition * 100, temporal * 100,
                 late_temporal * 100))
        print("  late silhouette: adjacent %.1f%%, +8 frames %.1f%% "
              "(normalised mask IoU loss)" %
              (late_shape * 100, late_advance * 100))
        if late_advance < 0.15:
            print("  WARNING: late gas silhouette is nearly frozen over 8 frames "
                  "— tune the source turbulence, not the particle emitter.")
    if args.shape == "column" and ratio < 1.3:
        print("  WARNING: still puff-shaped — raise --buoyancy or make the domain taller.")
    if reach >= 1.0 or clipped:
        print("  WARNING: CLIPPED at the cell border (%d frames) — re-render with "
              "--zoom auto; dialling zoom by hand cannot converge once clipped."
              % clipped)
    if live < want * 0.8:
        print("  WARNING: %d/%d frames are empty — bake or camera framing is off."
              % (want - live, want))


if __name__ == "__main__":
    sys.exit(main())
