#ifndef CORE_FLUID_COMPAT_FLUID_PBD_GPU_H
#define CORE_FLUID_COMPAT_FLUID_PBD_GPU_H

/* Legacy source compatibility. New code includes core/liquid/liquid_pbd_gpu.h. */
#include "core/liquid/liquid_pbd_gpu.h"

#define FLUID_PBD_GPU_MAX_PARTICLES LIQUID_PBD_GPU_MAX_PARTICLES
#define FluidPBDGPU_DrawSurfaceBackDepth LiquidPBDGPU_DrawSurfaceBackDepth
#define FluidPBDGPU_DrawSurfaceDepth LiquidPBDGPU_DrawSurfaceDepth
#define FluidPBDGPU_GetMaterial LiquidPBDGPU_GetMaterial
#define FluidPBDGPU_GetParticleCount LiquidPBDGPU_GetParticleCount
#define FluidPBDGPU_GetStateBuffer LiquidPBDGPU_GetStateBuffer
#define FluidPBDGPU_Init LiquidPBDGPU_Init
#define FluidPBDGPU_IsActive LiquidPBDGPU_IsActive
#define FluidPBDGPU_SpawnImpact LiquidPBDGPU_SpawnImpact
#define FluidPBDGPU_Unload LiquidPBDGPU_Unload
#define FluidPBDGPU_Update LiquidPBDGPU_Update
#define FluidSurface LiquidSurface

#endif
