#ifndef CORE_FLUID_COMPAT_FLUID_SURFACE_H
#define CORE_FLUID_COMPAT_FLUID_SURFACE_H

/* Legacy source compatibility. New code includes core/liquid/liquid_surface.h. */
#include "core/liquid/liquid_surface.h"
#include "core/fluid/fluid_motion.h"

#define FLUID_LIQUID_CONDUCTOR LIQUID_CLASS_CONDUCTOR
#define FLUID_LIQUID_DIELECTRIC LIQUID_CLASS_DIELECTRIC
#define FLUID_LIQUID_EMISSIVE LIQUID_CLASS_EMISSIVE
#define FLUID_PRIORITY_BASIC LIQUID_PRIORITY_BASIC
#define FLUID_PRIORITY_CAST LIQUID_PRIORITY_CAST
#define FLUID_PRIORITY_MINION LIQUID_PRIORITY_MINION
#define FLUID_PRIORITY_ULTIMATE LIQUID_PRIORITY_ULTIMATE
#define FLUID_SURFACE_BUDGET_MS LIQUID_SURFACE_BUDGET_MS
#define FLUID_SURFACE_COMPACT_BODY_PX LIQUID_SURFACE_COMPACT_BODY_PX
#define FLUID_SURFACE_COMPACT_KERNEL_PX LIQUID_SURFACE_COMPACT_KERNEL_PX
#define FLUID_SURFACE_MATERIAL_SLOTS LIQUID_SURFACE_MATERIAL_SLOTS
#define FLUID_SURFACE_MAX_PARTICLES LIQUID_SURFACE_MAX_PARTICLES
#define FLUID_SURFACE_MIN_PROJECTED_RADIUS_PX LIQUID_SURFACE_MIN_PROJECTED_RADIUS_PX
#define FluidLiquidClass LiquidClass
#define FluidLiquidDesc LiquidDesc
#define FluidMotionProfile LiquidMotionProfile
#define FluidMotion_Get LiquidMotion_Get
#define FluidSurfacePriority LiquidSurfacePriority
#define FluidSurface_BindMaterial LiquidSurface_BindMaterial
#define FluidSurface_Capture LiquidSurface_Capture
#define FluidSurface_Composite LiquidSurface_Composite
#define FluidSurface_CurrentMaterial LiquidSurface_CurrentMaterial
#define FluidSurface_DielectricDesc LiquidSurface_DielectricDesc
#define FluidSurface_HasPending LiquidSurface_HasPending
#define FluidSurface_HintBody LiquidSurface_HintBody
#define FluidSurface_Init LiquidSurface_Init
#define FluidSurface_ProfileDesc LiquidSurface_ProfileDesc
#define FluidSurface_RegisterEllipsoid LiquidSurface_RegisterEllipsoid
#define FluidSurface_RegisterParticle LiquidSurface_RegisterParticle
#define FluidSurface_RequestBody LiquidSurface_RequestBody
#define FluidSurface_SetMaterialColors LiquidSurface_SetMaterialColors
#define FluidSurface_SetReconstructionRadius LiquidSurface_SetReconstructionRadius
#define FluidSurface_SetReconstructionRadiusFor LiquidSurface_SetReconstructionRadiusFor
#define FluidSurface_SubmitParticleStream LiquidSurface_SubmitParticleStream
#define FluidSurface_Unload LiquidSurface_Unload

#endif
