#ifndef CORE_FLUID_COMPAT_FLUID_IMPACT_H
#define CORE_FLUID_COMPAT_FLUID_IMPACT_H

/* Legacy source compatibility. New code includes core/liquid/liquid_impact.h. */
#include "core/liquid/liquid_impact.h"
#include "core/fluid/fluid_motion.h"

#define FLUID_IMPACT_BACKEND_FORCE_FIELD LIQUID_IMPACT_BACKEND_FORCE_FIELD
#define FLUID_IMPACT_BACKEND_PBD LIQUID_IMPACT_BACKEND_PBD
#define FLUID_IMPACT_MAX_BODIES LIQUID_IMPACT_MAX_BODIES
#define FLUID_IMPACT_MAX_HERO_DROPLETS LIQUID_IMPACT_MAX_HERO_DROPLETS
#define FluidImpactBackend LiquidImpactBackend
#define FluidImpactCollision LiquidImpactCollision
#define FluidImpactCollisionQueryFn LiquidImpactCollisionQueryFn
#define FluidImpactEvent LiquidImpactEvent
#define FluidImpact_Draw LiquidImpact_Draw
#define FluidImpact_GetStats LiquidImpact_GetStats
#define FluidImpact_SetCollisionQuery LiquidImpact_SetCollisionQuery
#define FluidImpact_SpawnWater LiquidImpact_SpawnWater
#define FluidImpact_Update LiquidImpact_Update
#define FluidMotionProfile LiquidMotionProfile

#endif
