// Generated by scripts/process_dem_basin.py for song_quao
#ifndef SONG_QUAO_GENERATED_META_H
#define SONG_QUAO_GENERATED_META_H

#define SONG_QUAO_MAP_WIDTH      188.31f
#define SONG_QUAO_MAP_DEPTH      300.00f
#define SONG_QUAO_HEIGHT_RANGE   16.00f
#define SONG_QUAO_CLIFF_DEPTH    8.00f
#define SONG_QUAO_OUTLET_X       154.68f
#define SONG_QUAO_OUTLET_Z       210.27f
#define SONG_QUAO_PEAK_X         127.78f
#define SONG_QUAO_PEAK_Z         17.41f
#define SONG_QUAO_LAKE_CENTER_X  168.66f
#define SONG_QUAO_LAKE_CENTER_Z  229.37f
#define SONG_QUAO_LAKE_RADIUS_X  19.50f
#define SONG_QUAO_LAKE_RADIUS_Z  12.72f
#define SONG_QUAO_LAKE_WATER_Y   -2.66f
#define SONG_QUAO_LAKE_BED_MIN_Y -7.00f

#endif // SONG_QUAO_GENERATED_META_H
