// GENERATED by scripts/gen_materials.py from core/shading/materials/effect_material.mat.
// Do not edit this file by hand — CMake regenerates it at configure time.

#version 330
#include "core/shaders/common/fs_header.glsl"
#include "core/shaders/common/lighting.glsl"
#include "core/shaders/common/noise.glsl"
#include "core/shaders/common/fx.glsl"
#include "core/shaders/common/vfx_composite.glsl"

uniform vec4      u_baseColor;
uniform float     u_translucency;
uniform float     u_rimStrength;
uniform float     u_fresnelPower;
uniform float     u_emissiveIntensity;
uniform int       u_hasTexture1;
uniform sampler2D texture1;
uniform float     u_dissolve;
uniform float     u_vfxBodyOpacity;
uniform vec4      u_vfxEmissionColor;
uniform float     u_vfxEmissionIntensity;
uniform float     u_vfxCoreMask;
uniform vec3      u_lightDirView;

void main() {
    vec3 normal = normalize(fragNormal);
#if defined(OUTPUT_BODY) || defined(OUTPUT_EMISSION) || defined(OUTPUT_PREMULTIPLIED)
    // The opt-in path uses one coordinate contract: VS output, view vector and
    // sun direction are all view-space. Legacy output stays byte-for-byte on
    // its old convention until individual VFX are deliberately migrated.
    vec3 viewDir = normalize(-fragPosition);
    vec3 lightDir = normalize(u_lightDirView);
#else
    vec3 viewDir = normalize(viewPos - fragPosition);
    vec3 lightDir = normalize(u_lightDir);
#endif

    float diffuse = calcDiffuse(normal, lightDir, 0.2);
    float fresnel = calcFresnel(normal, viewDir, u_fresnelPower);

    vec3 baseColor = u_baseColor.rgb * diffuse;
    if (u_hasTexture1 != 0) {
        // Luminance-only mask (not detail.rgb) — texture1 is meant to modulate
        // brightness. Using Triplanar Mapping to avoid UV distortion on 
        // procedural meshes (spheres, rocks) and ensure seamless tiling.
        vec3 triBlend = abs(normal);
        triBlend /= (triBlend.x + triBlend.y + triBlend.z + 0.0001);
        
        float texScale = 2.0; // Scale lặp lại texture nhiều hơn để dễ thấy
        float maskX = texture(texture1, fragPosition.zy * texScale).r;
        float maskY = texture(texture1, fragPosition.xz * texScale).r;
        float maskZ = texture(texture1, fragPosition.xy * texScale).r;
        
        float detailMask = maskX * triBlend.x + maskY * triBlend.y + maskZ * triBlend.z;
        
        // Đảm bảo không bao giờ đen thui ngay cả khi detailMask = 0
        baseColor = baseColor * mix(0.5, 2.0, detailMask);
    }

#if !defined(OUTPUT_BODY) && !defined(OUTPUT_EMISSION) && !defined(OUTPUT_PREMULTIPLIED)
    // Compatibility path used by Material_LoadCustom and all existing presets.
    baseColor += baseColor * u_emissiveIntensity;
#endif

    // Weight the rim by how much this fragment faces the light, not just the
    // camera — plain view-only Fresnel glows evenly all the way around the
    // silhouette regardless of where the light actually is, which reads as
    // "rim doesn't match the light direction". Dimmed (not zeroed) on the
    // backlit side so the edge is still visible there, just weaker.
    float lightFacing = max(dot(normal, lightDir), 0.0);
    float rim = fresnel * mix(0.3, 1.0, lightFacing);
    baseColor += u_baseColor.rgb * rim * u_rimStrength;

    // Only evaluate dissolve/edge-glow once dissolve actually starts — fx.glsl's
    // dissolveCalc() computes edgeFactor for any noiseVal < dissolve + edgeWidth,
    // which is true for ~8% of fragments even at dissolve == 0.0 (the "still
    // solid" state). Left unguarded, that shows up as scattered bright speckle
    // dots across the whole surface the instant the material appears, well
    // before anything is meant to be dissolving.
    if (u_dissolve > 0.0) {
        // hash3 input uses `normal` (bounded [-1..1]), not fragPosition — fragPosition
        // is a raw world coordinate (arena center ~600), and hash3's internal
        // sin(dot(p, largeWeights)) loses precision badly at that magnitude. Using
        // normal also makes the dissolve pattern identical regardless of where in
        // the arena this material is drawn.
        float noiseVal = hash3(floor(normal * 20.0));
        float edgeFactor;
        if (dissolveCalc(noiseVal, u_dissolve, 0.08, edgeFactor) >= 1.0) discard;
        baseColor = mix(baseColor, u_baseColor.rgb * 2.0, edgeFactor);
    }

    // translucency == 0 -> fully opaque (existing behavior). translucency == 1 ->
    // same "center see-through, edges more solid" curve as tube.fs, driven by the
    // same fresnel term as the rim above. Caller must draw with BLEND_ALPHA
    // (BeginBlendMode/EndBlendMode) for the alpha<1 case to actually blend.
    float glassAlpha = mix(0.3, 0.9, fresnel);
    float alpha = mix(u_baseColor.a, glassAlpha, u_translucency);
#if defined(OUTPUT_BODY) || defined(OUTPUT_EMISSION) || defined(OUTPUT_PREMULTIPLIED)
    float outputCoverage = alpha * clamp(u_vfxBodyOpacity, 0.0, 1.0);
#if defined(OUTPUT_EMISSION)
    // Additive has no BODY coverage. Its alpha is the blend-unit energy/fade,
    // so bodyOpacity=0 must not erase a pure glow surface.
    outputCoverage = alpha;
#endif
    finalColor = VFX_ResolveOutput(
        baseColor, 1.0, outputCoverage,
        u_vfxEmissionColor.rgb, clamp(u_vfxCoreMask, 0.0, 1.0),
        max(u_vfxEmissionIntensity, 0.0));
#else
    finalColor = VFX_ResolveBody(baseColor, 1.0, alpha);
#endif
}
