// GENERATED by scripts/gen_materials.py from core/shading/materials/*.mat.
// Do not edit this file by hand.

/* core/shading/materials/aura_shell.mat — 14 parameters, output: body */
static const VfxParamDesc AURA_PARAMS[] = {
    P_COLOR("u_bodyColor", AuraShellMaterialParams, bodyColor),
    P_COLOR("u_glowColor", AuraShellMaterialParams, glowColor),
    P_FLOAT("u_opacity", AuraShellMaterialParams, opacity),
    P_FLOAT("u_fresnelPower", AuraShellMaterialParams, fresnelPower),
    P_FLOAT("u_rimStrength", AuraShellMaterialParams, rimStrength),
    P_FLOAT("u_scrollSpeed", AuraShellMaterialParams, scrollSpeed),
    P_FLOAT("u_noiseScale", AuraShellMaterialParams, noiseScale),
    P_FLOAT("u_heightScale", AuraShellMaterialParams, heightScale),
    P_FLOAT("u_scanFreq", AuraShellMaterialParams, scanFreq),
    P_FLOAT("u_scanSpeed", AuraShellMaterialParams, scanSpeed),
    P_FLOAT("u_scanStrength", AuraShellMaterialParams, scanStrength),
    P_FLOAT("u_displaceAmp", AuraShellMaterialParams, displaceAmp),
    P_FLOAT("u_heightFadeOff", AuraShellMaterialParams, heightFadeOff),
    P_FLOAT("u_coverFloor", AuraShellMaterialParams, coverFloor),
};
