// GENERATED by scripts/gen_materials.py from core/shading/materials/*.mat.
// Do not edit this file by hand.

/* core/shading/materials/aura_shell.mat — 15 parameters, output: body */
static const VfxParamDesc AURA_PARAMS[] = {
    P_COLOR("u_bodyColor", AuraShellMaterialParams, bodyColor),
    P_COLOR("u_glowColor", AuraShellMaterialParams, glowColor),
    P_FLOAT("u_opacity", AuraShellMaterialParams, opacity),
    P_FLOAT("u_fresnelPower", AuraShellMaterialParams, fresnelPower),
    P_FLOAT("u_rimStrength", AuraShellMaterialParams, rimStrength),
    P_FLOAT("u_scrollSpeed", AuraShellMaterialParams, scrollSpeed),
    P_FLOAT("u_noiseScale", AuraShellMaterialParams, noiseScale),
    P_FLOAT("u_heightScale", AuraShellMaterialParams, heightScale),
    P_FLOAT("u_scanFreq", AuraShellMaterialParams, scanFreq),
    P_FLOAT("u_scanSpeed", AuraShellMaterialParams, scanSpeed),
    P_FLOAT("u_scanStrength", AuraShellMaterialParams, scanStrength),
    P_FLOAT("u_displaceAmp", AuraShellMaterialParams, displaceAmp),
    P_FLOAT("u_heightFadeOff", AuraShellMaterialParams, heightFadeOff),
    P_FLOAT("u_coverFloor", AuraShellMaterialParams, coverFloor),
    P_FLOAT("u_sphereDomain", AuraShellMaterialParams, sphereDomain),
};

/* core/shading/materials/crystal.mat — 12 parameters, output: premultiplied */
static const VfxParamDesc CRYSTAL_PARAMS[] = {
    P_COLOR("u_baseColor", CrystalMaterialParams, baseColor),
    P_COLOR("u_edgeColor", CrystalMaterialParams, edgeColor),
    P_AFFINE("u_fresnelPower", CrystalMaterialParams, roughness, 8.0f, -7.0f, 1.0f, 1e30f),
    P_FLOAT("u_rimStrength", CrystalMaterialParams, fresnel),
    P_FLOAT("u_refraction", CrystalMaterialParams, refraction),
    P_FLOAT("u_sparkle", CrystalMaterialParams, sparkle),
    P_FLOAT("u_crack", CrystalMaterialParams, crack),
    P_FLOAT("u_emission", CrystalMaterialParams, emission),
    P_FLOAT("u_thickness", CrystalMaterialParams, thickness),
    P_FLOAT("u_dissolve", CrystalMaterialParams, dissolve),
    P_TEX("texture1", CrystalMaterialParams, texture1),
    P_CONST("u_growProgress", 1.0f),
};

/* Texture defaults: applied when the caller left the field at id 0. */
static const VfxTextureDefault CRYSTAL_PARAMS_DEFAULTS[] = {
    { offsetof(CrystalMaterialParams, texture1), "assets/textures/tex_crystal.png" },
};

/* core/shading/materials/effect_material.mat — 9 parameters, output: premultiplied */
static const VfxParamDesc EFFECT_PARAMS[] = {
    P_COLOR("u_baseColor", EffectMaterialParams, baseColor),
    P_FLOAT("u_translucency", EffectMaterialParams, translucency),
    P_FLOAT("u_rimStrength", EffectMaterialParams, rimStrength),
    P_FLOAT("u_fresnelPower", EffectMaterialParams, fresnelPower),
    P_FLOAT("u_emissiveIntensity", EffectMaterialParams, emissiveIntensity),
    P_TEXFLAG("u_hasTexture1", EffectMaterialParams, texture1),
    P_TEX("texture1", EffectMaterialParams, texture1),
    P_FLOAT("u_distortionStrength", EffectMaterialParams, distortionStrength),
};

/* Presets: authored parameter sets, indexed by the enum. */
static const EffectMaterialParams EFFECT_PARAMS_PRESETS[] = {
    [MAT_FIRE] = { .baseColor = ELEMENT_COLOR_FIRE, .rimStrength = 1.2f, .fresnelPower = 3.0f, .emissiveIntensity = 1.5f, .distortionStrength = 0.4f, .translucency = 0.0f },
    [MAT_ICE] = { .baseColor = ((Color){170, 220, 255, 150}), .rimStrength = 1.5f, .fresnelPower = 5.0f, .emissiveIntensity = 0.5f, .distortionStrength = 0.0f, .translucency = 0.6f },
    [MAT_WATER] = { .baseColor = ELEMENT_COLOR_WATER, .rimStrength = 1.0f, .fresnelPower = 4.0f, .emissiveIntensity = 0.6f, .distortionStrength = 0.25f, .translucency = 0.85f },
    [MAT_PORTAL] = { .baseColor = ELEMENT_COLOR_TAIJI, .rimStrength = 2.0f, .fresnelPower = 2.0f, .emissiveIntensity = 2.0f, .distortionStrength = 0.6f, .translucency = 0.3f },
    [MAT_ROCK] = { .baseColor = ((Color){150, 110, 80, 255}), .rimStrength = 0.3f, .fresnelPower = 2.0f, .distortionStrength = 0.0f, .translucency = 0.0f },
    [MAT_METAL] = { .baseColor = ELEMENT_COLOR_METAL, .rimStrength = 1.8f, .fresnelPower = 6.0f, .emissiveIntensity = 1.0f, .distortionStrength = 0.08f, .translucency = 0.2f },
    [MAT_GLASS] = { .baseColor = ((Color){200, 230, 255, 100}), .rimStrength = 1.5f, .fresnelPower = 4.0f, .emissiveIntensity = 0.2f, .distortionStrength = 0.1f, .translucency = 0.9f },
};

/* A preset's texture is LOADED, so it cannot live in the
 * initializer above — it is a path resolved at Get() time. */
static const char *EFFECT_PARAMS_PRESET_TEXTURES[] = {
    [MAT_ICE] = "assets/textures/tex_ice_crystal.png",
    [MAT_ROCK] = "assets/textures/tex_rock_albedo.png",
};
