// ── E5.2 — VFX_ComposeRuneCircle ─────────────────────────────────────────────
//
// The layered sigil every caster skill wants: `ringCount` concentric rings on a
// plane, counter-rotating, snapping open and easing shut on `t01`.
//
// BUILT ON THE REBUILT FOUNDATION ONLY (Đợt E is a restructure): geometry from
// `ribbon_strip` (the project's one ribbon primitive), colours from
// `VFX_Material`, motion from `vc_motion.h`. It deliberately does NOT reuse
// `MagicFilaments` or `GroundAura` even though both draw circles — those are the
// one-surface-plus-FBM architecture §0.1b diagnoses as the disease, and the spec
// says outright there is *no layered sigil* in the project.
//
// WHY RIBBONS RATHER THAN A DECAL OR A TEXTURED QUAD. A sigil has to sit on an
// arbitrary plane (the `normal` argument) — a ground decal cannot, it is stuck
// flat on the terrain. And per §0.1b the silhouette must come from geometry, not
// from noise inside a quad. A closed ribbon gives a real band with real width
// that can be read edge-on.
//
// GLYPHS WITHOUT AN ATLAS. E4's glyph sheet does not exist, and the spec requires
// a procedural fallback. Rather than draw fake letterforms, the rings are
// DASHED: alpha is switched along the band, so each ring reads as a sequence of
// marks. The dash pattern is derived from a per-ring seed, so ring 0 and ring 1
// never share a rhythm and the whole thing reads as writing rather than as a
// dotted line. An authored sheet is still preferred if one ever lands.
//
// BLEND LAW (§F1b): a sigil EMITS, so additive, and — per the spec — depth-test
// on, depth-write off, with the batch flushed either side (ENGINE_LANDMINES §1).
//
// COLOUR: near-white body with the element hue at the edges, the same decision
// as the charge threads — white keeps the element a TINT applied by the caller
// rather than something baked into the geometry.

#define RUNE_MAX_RINGS   4
#define RUNE_RING_POINTS 97      // 96 segments + the duplicated closing point

static SkillCurve s_runeOpen = {0};   // radius vs t01: snaps open, eases shut
static SkillCurve s_runeFade = {0};   // alpha vs t01
static bool       s_runeInit = false;

static float s_runeWhite = 0.25f;     // how white the band is (element = tint)
static float s_runeWidth = 1.0f;      // x on band thickness
static float s_runeSpin  = 1.0f;      // x on rotation speed
static float s_runeDash  = 1.0f;      // x on dash density

// The band's cross-section: bright filament in the middle, soft falloff, hard
// zero at both edges. Without it the band is a flat rectangle with a hard cut
// edge — the single biggest difference between "a ring" and "a glowing line".
// Falls back to flat white if the asset is missing, so the component still works.
static Texture2D s_runeTex = {0};
// One glyph strip per ring, so no two rings carry the same writing. Generated by
// scripts/gen_rune_textures.py (procedural strokes — a font would have to exist
// on every machine, and an image model cannot guarantee a seamless wrap, a
// uniform glyph height or a clean alpha).
#define RUNE_GLYPH_SHEETS 4
static Texture2D s_runeGlyph[RUNE_GLYPH_SHEETS] = {0};

static void Rune_InitShared(void)
{
    if (s_runeInit) return;

    // "Snaps open and eases shut" (spec): overshoot early, hold, collapse at the
    // end. The overshoot is what makes it read as STAMPED rather than grown.
    FloatCurve_AddStop(&s_runeOpen, 0.00f, 0.05f);
    FloatCurve_AddStop(&s_runeOpen, 0.12f, 1.06f);
    FloatCurve_AddStop(&s_runeOpen, 0.22f, 1.00f);
    FloatCurve_AddStop(&s_runeOpen, 0.82f, 0.98f);
    FloatCurve_AddStop(&s_runeOpen, 1.00f, 0.55f);

    FloatCurve_AddStop(&s_runeFade, 0.00f, 0.0f);
    FloatCurve_AddStop(&s_runeFade, 0.08f, 1.0f);
    FloatCurve_AddStop(&s_runeFade, 0.80f, 1.0f);
    FloatCurve_AddStop(&s_runeFade, 1.00f, 0.0f);

    Tuning_RegisterFloat("rune_white", &s_runeWhite, 0.25f);
    Tuning_RegisterFloat("rune_width", &s_runeWidth, 1.0f);
    Tuning_RegisterFloat("rune_spin",  &s_runeSpin,  1.0f);
    Tuning_RegisterFloat("rune_dash",  &s_runeDash,  1.0f);

    s_runeTex = ResourceManager_LoadTexture("assets/textures/rune_line.png");
    if (s_runeTex.id == 0)
    {
        TraceLog(LOG_WARNING, "RuneCircle: rune_line.png missing, using flat white band");
        Image wimg = GenImageColor(4, 4, WHITE);
        s_runeTex = LoadTextureFromImage(wimg);
        UnloadImage(wimg);
    }
    else SetTextureFilter(s_runeTex, TEXTURE_FILTER_BILINEAR);

    for (int g = 0; g < RUNE_GLYPH_SHEETS; g++)
    {
        char path[96];
        snprintf(path, sizeof(path), "assets/textures/rune_glyphs_%d.png", g);
        s_runeGlyph[g] = ResourceManager_LoadTexture(path);
        if (s_runeGlyph[g].id != 0)
        {
            SetTextureFilter(s_runeGlyph[g], TEXTURE_FILTER_BILINEAR);
            // The strip wraps the ring; without REPEAT the last texel smears
            // around the whole circumference.
            SetTextureWrap(s_runeGlyph[g], TEXTURE_WRAP_REPEAT);
        }
    }
    if (s_runeGlyph[0].id == 0)
        TraceLog(LOG_WARNING, "RuneCircle: rune_glyphs_*.png missing — "
                              "falling back to dashed rings (run scripts/gen_rune_textures.py)");

    s_runeInit = true;
}

// An orthonormal basis for the sigil's plane. `normal` may be anything; the
// reference axis is swapped near the pole so the cross product never degenerates
// (the same guard VC_DirCone uses).
static void Rune_PlaneBasis(Vector3 normal, Vector3 *outU, Vector3 *outV)
{
    Vector3 n = Vector3Normalize(normal);
    Vector3 ref = (fabsf(n.y) < 0.99f) ? (Vector3){0.0f, 1.0f, 0.0f}
                                       : (Vector3){1.0f, 0.0f, 0.0f};
    *outU = Vector3Normalize(Vector3CrossProduct(n, ref));
    *outV = Vector3CrossProduct(n, *outU);
}

// The dash pattern of one ring: 1 = mark, 0 = gap, with soft shoulders so the
// ends of a mark are not hard-cut (a hard cut aliases badly on a thin band).
// Closed-form, NO noise hash: `fract(sin(...))` dies on Mali (ENGINE_LANDMINES §4).
static float Rune_DashMask(int ring, float a01)
{
    // Different tooth count and phase per ring, so no two rings share a rhythm.
    float teeth = (float)(7 + ring * 5) * s_runeDash;
    float phase = (float)ring * 0.37f;
    float x = (a01 * teeth + phase);
    float f = x - floorf(x);
    // Duty cycle also varies per ring: outer rings read as long marks, inner
    // rings as short ticks.
    float duty = 0.62f - 0.10f * (float)(ring % 3);
    if (f > duty) return 0.0f;
    float edge = 0.12f;
    float head = (f < edge) ? (f / edge) : 1.0f;
    float tail = (f > duty - edge) ? ((duty - f) / edge) : 1.0f;
    return fminf(head, tail);
}

// Continuous: call once per frame with the caster's progress.
// `normal` = the plane's normal ((0,1,0) = flat on the ground).
// `t01`    = 0→1 open/hold/close. `ringCount` clamped to RUNE_MAX_RINGS.
void VFX_ComposeRuneCircle(Vector3 center, Vector3 normal, VC_MaterialId mat,
                           float radius, float t01, int ringCount)
{
    Rune_InitShared();
    if (radius <= 0.0f) radius = 1.0f;
    if (t01 < 0.0f) t01 = 0.0f;
    if (t01 > 1.0f) t01 = 1.0f;
    if (ringCount < 1) ringCount = 1;
    if (ringCount > RUNE_MAX_RINGS) ringCount = RUNE_MAX_RINGS;

    const VFX_ElementMaterial *m = VFX_Material(mat);
    float open  = SkillCurve_Eval(&s_runeOpen, t01);
    float fade  = SkillCurve_Eval(&s_runeFade, t01);
    if (fade <= 0.001f) return;

    Vector3 u, v;
    Rune_PlaneBasis(normal, &u, &v);
    float time = (float)GetTime();

    Color bodyCol = VC_Whiten(m->glow, s_runeWhite);
    Color edgeCol = m->body;

    // Additive, depth-test on / depth-write off, batch flushed either side —
    // ENGINE_LANDMINES §1: a depth-state change that is not flushed leaks into
    // whatever the batch was already holding.
    rlDrawRenderBatchActive();
    BeginBlendMode(BLEND_ADDITIVE);
    rlDisableDepthMask();
    rlDrawRenderBatchActive();

    static RibbonPoint pts[RUNE_RING_POINTS];

    // Three passes per ring. A ribbon goes through the immediate-mode path, so
    // unlike a particle it has NO emissiveBoost uniform — its vertex colour is
    // 8-bit and caps at 1.0, which is under the bloom threshold's reach. The
    // way to exceed 1.0 in the HDR buffer with plain geometry is to draw it
    // ADDITIVELY more than once: a wide dim halo, the band itself, then a
    // narrow near-white core drawn on top. That layering is also what stops an
    // additive band from reading as flat paint.
    static const float passW[3] = { 3.4f, 1.0f, 0.42f };   // x on half-width
    static const float passA[3] = { 0.22f, 0.85f, 1.0f };  // x on alpha
    static const float passWhite[3] = { 0.0f, 0.5f, 1.0f };// extra whitening

    // A glyph ring gets only TWO passes: a dim halo underneath and the writing
    // itself. The third pass exists to put a white-hot filament down the middle
    // of a plain band — on a glyph ring it would paint straight over the text.
    // Three for glyph rings as well. The third is the SAME sheet drawn a second
    // time rather than a filament down the middle (which would cross out the
    // writing): additive geometry has no emissiveBoost, so re-drawing is the
    // only way its pixels get past 1.0 and into the bloom's reach.
    static const float glyphW[3] = { 2.4f, 1.0f, 0.92f };
    static const float glyphA[3] = { 0.28f, 1.0f, 0.85f };
    static const float glyphWhite[3] = { 0.0f, 0.30f, 0.85f };

    for (int r = 0; r < ringCount; r++)
    {
        // Alternating written / plain rings, which is what gives the sigil its
        // hierarchy — a stack of identical rings reads as a target, not a seal.
        bool isGlyph = (r % 2 == 0) && (s_runeGlyph[r % RUNE_GLYPH_SHEETS].id != 0);
        int  passes  = 3;
        // Rings alternate spin direction (spec) and slow down as they go inward,
        // so the sigil never reads as one rigid object turning.
        float dir   = (r % 2 == 0) ? 1.0f : -1.0f;
        float speed = (0.55f + 0.22f * (float)r) * dir * s_runeSpin;
        float spin  = time * speed;

        // Concentric radii, and the whole set is driven by the open curve.
        float rr = radius * open * (1.0f - 0.19f * (float)r);
        // Thin bands: a sigil is drawn with a pen, not painted with a roller.
        // A written ring has to be wide enough for its glyphs to be legible,
        // which is a different job from a plain ring's hairline.
        float halfW = radius * (isGlyph ? 0.075f : (0.022f - 0.003f * (float)r))
                             * s_runeWidth;
        // Each ring breathes on its own phase — a static ring next to a moving
        // one is what makes a sigil look like a UI widget.
        halfW *= VC_Breathe(time + (float)r, 2.1f + 0.4f * (float)r, 0.12f);

        for (int pass = 0; pass < passes; pass++)
        {
            // The halo pass under a glyph ring uses the plain band profile —
            // the glyph sheet is mostly empty, so haloing it would just double
            // the letterforms instead of putting light behind them.
            bool glyphPass = isGlyph && pass >= 1;
            Texture2D tex = glyphPass ? s_runeGlyph[r % RUNE_GLYPH_SHEETS] : s_runeTex;
        for (int i = 0; i < RUNE_RING_POINTS; i++)
        {
            float a01 = (float)i / (float)(RUNE_RING_POINTS - 1);
            float ang = a01 * 2.0f * PI + spin;
            Vector3 p = Vector3Add(center,
                          Vector3Add(Vector3Scale(u, cosf(ang) * rr),
                                     Vector3Scale(v, sinf(ang) * rr)));
            pts[i].position  = p;
            pts[i].halfWidth = halfW * (isGlyph ? glyphW[pass] : passW[pass]);
            pts[i].v         = a01;

            // The dash pattern rides the RING's own angle (a01), not world
            // angle, so the marks rotate with the ring instead of the ring
            // sliding underneath a stationary pattern.
            // A written ring needs no dash — the glyph sheet's own alpha IS the
            // pattern. Dashing it too would chop the letters in half.
            // The innermost plain ring is never dashed. Its circumference is the
            // shortest, so the same dash pattern that reads as marks on a big
            // ring reads there as the ring simply being broken — which is what
            // the owner saw.
            bool solid = isGlyph || (r == ringCount - 1);
            float mask = solid ? 1.0f : Rune_DashMask(r, a01);
            // Hue rides the mark's own intensity: the bright middle of a mark is
            // near-white, its shoulders carry the element colour. That is the
            // cheapest way to keep an additive band from reading as flat paint.
            Color c = (mask > 0.75f) ? bodyCol : edgeCol;
            c = VC_Whiten(c, isGlyph ? glyphWhite[pass] : passWhite[pass]);
            float a = fade * mask * (0.95f - 0.12f * (float)r)
                           * (isGlyph ? glyphA[pass] : passA[pass]);
            pts[i].tint = ColorAlpha(c, a);
        }

        DrawRibbonStripEx(pts, RUNE_RING_POINTS, tex, camera,
                          RIBBON_FIXED_NORMAL, normal);
        }
    }

    rlDrawRenderBatchActive();
    rlEnableDepthMask();
    EndBlendMode();
    rlDrawRenderBatchActive();

}
