#!/usr/bin/env python3
"""Generate the immutable 64x64 fog sampling ranks; NumPy is authoring-only."""
from pathlib import Path
import numpy as np

SIZE = 64
SEED = 0x574658


def generate():
    rng = np.random.default_rng(SEED)
    count = SIZE * SIZE
    coords = np.minimum(np.arange(SIZE), SIZE - np.arange(SIZE))
    kernel = np.exp(-(coords[:, None] ** 2 + coords[None, :] ** 2) / (2 * 1.9 ** 2))
    kernel_fft = np.fft.fft2(kernel)

    def density(pattern):
        return np.fft.ifft2(np.fft.fft2(pattern) * kernel_fft).real

    def stamp(index):
        y, x = divmod(int(index), SIZE)
        return np.roll(kernel, (y, x), axis=(0, 1))

    pattern = np.zeros(count, dtype=bool)
    pattern[rng.permutation(count)[:count // 10]] = True
    pattern = pattern.reshape(SIZE, SIZE)
    field = density(pattern)
    for _ in range(count * 8):
        cluster = np.argmax(np.where(pattern, field, -np.inf))
        pattern.flat[cluster] = False
        field -= stamp(cluster)
        void = np.argmin(np.where(~pattern, field, np.inf))
        pattern.flat[void] = True
        field += stamp(void)
        if void == cluster:
            break
    else:
        raise RuntimeError('void/cluster relaxation did not converge')

    ranks = np.empty((SIZE, SIZE), dtype=np.int32)
    initial = pattern.copy()
    initial_count = int(pattern.sum())
    for rank in range(initial_count - 1, -1, -1):
        index = np.argmax(np.where(pattern, field, -np.inf))
        ranks.flat[index] = rank
        pattern.flat[index] = False
        field -= stamp(index)

    pattern = initial
    field = density(pattern)
    for rank in range(initial_count, count // 2):
        index = np.argmin(np.where(~pattern, field, np.inf))
        ranks.flat[index] = rank
        pattern.flat[index] = True
        field += stamp(index)

    pattern = ~pattern
    field = density(pattern)
    for rank in range(count // 2, count):
        index = np.argmax(np.where(pattern, field, -np.inf))
        ranks.flat[index] = rank
        pattern.flat[index] = False
        field -= stamp(index)

    assert len(np.unique(ranks)) == count
    return (ranks * 256 // count).astype(np.uint8)


def main():
    data = generate()
    destination = Path(__file__).resolve().parents[1] / 'fog_blue_noise.h'
    rows = ['    ' + ', '.join(str(int(v)) for v in row) + ','
            for row in data.reshape(-1, 16)]
    destination.write_text(
        '// Generated by tools/generate_fog_blue_noise.py; seed 0x574658.\n'
        '#ifndef WUXING_FOG_BLUE_NOISE_H\n#define WUXING_FOG_BLUE_NOISE_H\n\n'
        '#define FOG_BLUE_NOISE_SIZE 64\n'
        'static const unsigned char kFogBlueNoise[FOG_BLUE_NOISE_SIZE * FOG_BLUE_NOISE_SIZE] = {\n'
        + '\n'.join(rows) + '\n};\n\n#endif\n')
    print(destination)


if __name__ == '__main__':
    main()
