// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_MAP_REGISTRY.PY - DO NOT MODIFY MANUAL
#ifndef MAPS_GENERATED_H
#define MAPS_GENERATED_H

#include "core/map_manager.h"

#include "maps/default_arena/default_arena.h"

static inline void RegisterGeneratedMaps(void) {
    MapManager_Register("DEFAULT_ARENA", InitDefaultArenaMap, NULL, DrawDefaultArenaMap, NULL);
}

#endif // MAPS_GENERATED_H
