// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_MAP_REGISTRY.PY - DO NOT MODIFY MANUAL
#ifndef MAPS_GENERATED_H
#define MAPS_GENERATED_H

#include "core/map_manager.h"

#include "maps/meadow_night/meadow_night.h"
#include "maps/soft_test_ground/soft_test_ground.h"
#include "maps/bamboo_valley/bamboo_valley.h"
#include "maps/default_arena/default_arena.h"

static inline void RegisterGeneratedMaps(void) {
    MapManager_Register("MEADOW_NIGHT", InitMeadowNightMap, UpdateMeadowNightMap, DrawMeadowNightMap, UnloadMeadowNightMap);
    MapManager_Register("SOFT_TEST_GROUND", InitSoftTestGroundMap, NULL, DrawSoftTestGroundMap, UnloadSoftTestGroundMap);
    MapManager_Register("BAMBOO_VALLEY", InitBambooValleyMap, UpdateBambooValleyMap, DrawBambooValleyMap, UnloadBambooValleyMap);
    MapManager_Register("DEFAULT_ARENA", InitDefaultArenaMap, NULL, DrawDefaultArenaMap, NULL);
}

#endif // MAPS_GENERATED_H
