// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_REGISTRY.PY - DO NOT MODIFY MANUAL
#ifndef SKILLS_GENERATED_H
#define SKILLS_GENERATED_H

#include "core/skill_manager.h"


static inline void RegisterGeneratedSkills(void) {
}

#endif // SKILLS_GENERATED_H
