#ifndef DECAL_MATERIAL_TYPES_H
#define DECAL_MATERIAL_TYPES_H

typedef enum {
    DECAL_MATERIAL_IMPACT = 0,
    DECAL_MATERIAL_SCORCH,
    DECAL_MATERIAL_FROST,
    DECAL_MATERIAL_COUNT
} DecalMaterialId;

#endif // DECAL_MATERIAL_TYPES_H
