#!/usr/bin/env python3
"""Compile core/shading/materials/*.mat into GLSL + the C parameter tables.

WHY THIS IS A BUILD-TIME TOOL AND NOT A RUNTIME PARSER
------------------------------------------------------
Filament's own material system works this way — `matc` compiles a `.mat` offline
and the engine loads the result — and so does everything else generated in this
repo (gen_vfx_surface_registry.py, generate_registry.py, generate_map_registry.py
all run at CMake configure time). A runtime parser would mean allocation, parse
errors on a player's device, and a second code path on Android for something
whose inputs never change after the build.

WHAT A .mat REPLACES
--------------------
Before this, a material's uniform list existed TWICE: once as `uniform` lines in
the .fs, and once as a VfxParamDesc table hand-written in material_system.c. The
two drifted, silently, because nothing compared them — authoring the first .mat
turned up `u_topY`, which the C table had been fetching for a uniform no shader
declares, while a consumer carefully set its value every frame. A .mat is the one
list both are generated from.

OUTPUTS (both overwritten every configure; do not hand-edit either)
  core/shaders/<name>.fs                  the fragment program
  core/material/materials.generated.inl   the VfxParamDesc tables
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAT_DIR = ROOT / "core" / "shading" / "materials"
SHADER_OUT_DIR = ROOT / "core" / "shaders"
TABLE_OUT = ROOT / "core" / "material" / "materials.generated.inl"

BANNER_GLSL = ("// GENERATED by scripts/gen_materials.py from {src}.\n"
               "// Do not edit this file by hand — CMake regenerates it at configure time.\n")
BANNER_C = ("// GENERATED by scripts/gen_materials.py from core/shading/materials/*.mat.\n"
            "// Do not edit this file by hand.\n")

# kind -> (GLSL type, the P_* macro, needs a struct field)
# No "time" kind on purpose: u_time is auto-bound by SkillManager_BeginShader
# and only by it (core/shaders/common/fs_header.glsl). A material that pushes
# its own overwrites a clock accumulated from the pinned delta with the wall
# clock, which is reproducible in-game and NOT reproducible headless.
# kind -> (GLSL type, P_* macro, needs a struct `field`)
#   float   a float field, optionally through an affine map (see a/b/lo/hi)
#   color   a Color field, pushed as a normalized vec4
#   texture a Texture2D field
#   texflag the same Texture2D field, pushed as int(id != 0)
#   const   a literal the material always pushes; no field
#   extern  DECLARED in GLSL but NOT in the table: something sets it by name at
#           runtime (Material_SetFloat). Without this the generator would emit a
#           shader that references an undeclared uniform and fails to compile.
#
# A `texture` parameter may carry `default: "path"`. The loader uses it when the
# caller left the field's id at 0, which is how a material stops being the thing
# that hardcodes an asset path in C.
#
# NOT a vfx_surface_registry role. assets/TEXTURE_PACKING.md scopes that registry
# to packed VFX sheets and puts conventional albedo/detail maps explicitly
# outside it — which is what every material texture here is.
KINDS = {
    "float":   ("float",     "P_FLOAT",   True),
    "color":   ("vec4",      "P_COLOR",   True),
    "texture": ("sampler2D", "P_TEX",     True),
    "texflag": ("int",       "P_TEXFLAG", True),
    "const":   ("float",     "P_CONST",   False),
    "extern":  ("float",     None,        False),
}
OUTPUTS = {"body", "emission", "premultiplied"}
OUTPUT_RESOLVER = {
    "body": "VFX_ResolveBody",
    "emission": "VFX_ResolveEmission",
    "premultiplied": "VFX_ResolvePremultiplied",
}
OUTPUT_SURFACE = {
    "body": "VFX_SURFACE_ALPHA",
    "emission": "VFX_SURFACE_ADDITIVE",
    "premultiplied": "VFX_SURFACE_PREMULTIPLIED",
}


class MatError(Exception):
    pass


def strip_comments(text):
    """Remove // comments, but never inside a quoted string."""
    out = []
    for line in text.split("\n"):
        quoted = False
        cut = len(line)
        i = 0
        while i < len(line) - 1:
            if line[i] == '"':
                quoted = not quoted
            elif not quoted and line[i] == "/" and line[i + 1] == "/":
                cut = i
                break
            i += 1
        out.append(line[:cut])
    return "\n".join(out)


def split_blocks(text, src):
    """Return (material_block_text, fragment_block_text) by brace matching.

    Brace matching rather than a regex: the fragment block is GLSL and is full of
    braces, so anything that stops at the first '}' truncates the shader — which
    would still emit a file, and a file that compiles to something wrong is worse
    than one that fails.
    """
    blocks = {}
    for name in ("material", "fragment"):
        m = re.search(r"\b%s\s*\{" % name, text)
        if not m:
            raise MatError("%s: missing `%s {` block" % (src, name))
        depth, i = 0, m.end() - 1
        while i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    blocks[name] = text[m.end():i]
                    break
            i += 1
        else:
            raise MatError("%s: `%s {` block is never closed" % (src, name))
    return blocks["material"], blocks["fragment"]


def parse_scalar(body, key, src, required=True):
    m = re.search(r"\b%s\s*:\s*([^,\n]+)" % key, body)
    if not m:
        if required:
            raise MatError("%s: material block has no `%s`" % (src, key))
        return None
    return m.group(1).strip().strip('"').rstrip(",").strip()


def parse_list(body, key):
    m = re.search(r"\b%s\s*:\s*\[(.*?)\]" % key, body, re.S)
    if not m:
        return []
    return [v.strip().strip('"') for v in m.group(1).split(",") if v.strip()]


def extract_list(body, key):
    """The [...] that follows `key:`, matched by BRACKET DEPTH.

    A greedy regex runs to the last ] in the whole block, so with two list keys
    present (`presets` and `parameters`) it hands back both concatenated. That is
    how the first attempt at presets fed parameter entries into the preset parser.
    """
    m = re.search(r"\b%s\s*:\s*\[" % key, body)
    if not m:
        return None
    depth, i = 0, m.end() - 1
    while i < len(body):
        if body[i] == "[":
            depth += 1
        elif body[i] == "]":
            depth -= 1
            if depth == 0:
                return body[m.end():i]
        i += 1
    raise MatError("`%s` list is never closed" % key)


def split_entries(text):
    r"""Every brace-balanced {...} body in `text`, at nesting depth 1.

    A regex like \{([^}]*)\} cannot do this: a preset value is a C expression
    and may itself contain braces — `(Color){170, 220, 255, 150}` — which would
    end the entry early and silently truncate it.
    """
    out, depth, start = [], 0, None
    for i, ch in enumerate(text):
        if ch == "{":
            depth += 1
            if depth == 1:
                start = i + 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                out.append(text[start:i])
                start = None
    return out


def split_fields(entry):
    """`key: value` pairs, splitting only on commas at brace depth 0.

    Same reason as above: `baseColor: (Color){170, 220, 255, 150}` holds three
    commas that belong to the value, not to the field list.
    """
    fields, depth, buf = {}, 0, []
    for ch in entry + ",":
        if ch in "{([":
            depth += 1
        elif ch in "})]":
            depth -= 1
        if ch == "," and depth == 0:
            piece = "".join(buf).strip()
            buf = []
            if ":" in piece:
                k, v = piece.split(":", 1)
                fields[k.strip()] = v.strip()
            continue
        buf.append(ch)
    return fields


def parse_parameters(body, src):
    listing = extract_list(body, "parameters")
    if listing is None:
        raise MatError("%s: material block has no `parameters`" % src)
    params = []
    for entry in split_entries(listing):
        fields = split_fields(entry)
        if "uniform" not in fields or "kind" not in fields:
            raise MatError("%s: parameter needs both `uniform` and `kind`: {%s}"
                           % (src, entry.strip()))
        kind = fields["kind"]
        if kind == "time" or fields["uniform"] == "u_time":
            raise MatError(
                "%s: a material must not declare u_time. It is auto-bound by "
                "SkillManager_BeginShader from the pinned clock; pushing your "
                "own replaces it with the wall clock and the effect stops being "
                "reproducible headless." % src)
        if kind not in KINDS:
            raise MatError("%s: unknown kind `%s` on %s (known: %s)"
                           % (src, kind, fields["uniform"], ", ".join(sorted(KINDS))))
        if KINDS[kind][2] and "field" not in fields:
            raise MatError("%s: `%s` is kind %s and needs a `field`"
                           % (src, fields["uniform"], kind))
        if "default" in fields and kind != "texture":
            raise MatError("%s: `%s` has a default but only a texture may carry one"
                           % (src, fields["uniform"]))
        if kind == "const" and "value" not in fields:
            raise MatError("%s: `%s` is kind const and needs a `value`"
                           % (src, fields["uniform"]))
        if kind == "extern" and "glsl" in fields and fields["glsl"] not in (
                "float", "vec2", "vec3", "vec4", "int", "sampler2D"):
            raise MatError("%s: `%s` has unknown glsl type `%s`"
                           % (src, fields["uniform"], fields["glsl"]))
        params.append(fields)
    if not params:
        raise MatError("%s: `parameters` is empty" % src)
    return params


def parse_presets(body, src):
    """Optional. A preset is a named set of param-struct defaults — the Material
    Instance idea: one shader, one table, many authored looks. Values are C
    expressions and are emitted verbatim, so a preset can say ELEMENT_COLOR_FIRE
    and mean the engine's constant."""
    listing = extract_list(body, "presets")
    if listing is None:
        return []
    presets = []
    for entry in split_entries(listing):
        fields = split_fields(entry)
        if "name" not in fields:
            raise MatError("%s: a preset needs a `name` (the MaterialPreset enum)" % src)
        presets.append(fields)
    return presets


def parse_mat(path):
    raw = path.read_text()
    src = str(path.relative_to(ROOT))
    material, fragment = split_blocks(raw, src)
    material = strip_comments(material)

    mat = {
        "src": src,
        "name": parse_scalar(material, "name", src),
        "output": parse_scalar(material, "output", src),
        "table": parse_scalar(material, "table", src),
        "struct": parse_scalar(material, "struct", src),
        "includes": parse_list(material, "includes"),
        "parameters": parse_parameters(material, src),
        "presets": parse_presets(material, src),
        "fragment": fragment,
    }
    if mat["output"] not in OUTPUTS:
        raise MatError("%s: output `%s` is not one of %s"
                       % (src, mat["output"], ", ".join(sorted(OUTPUTS))))

    # `output` is a render contract, not documentation. A material may call its
    # fixed resolver or use VFX_ResolveOutput with a loader-selected permutation.
    fragment_code = strip_comments(mat["fragment"])
    expected_resolver = OUTPUT_RESOLVER[mat["output"]]
    if ("VFX_ResolveOutput" not in fragment_code and
            expected_resolver not in fragment_code):
        raise MatError(
            "%s: output `%s` requires %s or VFX_ResolveOutput"
            % (src, mat["output"], expected_resolver))

    seen = set()
    for p in mat["parameters"]:
        if p["uniform"] in seen:
            raise MatError("%s: `%s` listed twice" % (src, p["uniform"]))
        seen.add(p["uniform"])

    # A preset may only set fields the parameters actually bind. Catching a typo
    # here beats emitting a C initializer for a field that does not exist and
    # letting the compiler point at generated code.
    known = {p["field"] for p in mat["parameters"] if "field" in p}
    for preset in mat["presets"]:
        for key in preset:
            if key in ("name", "texture_path"):
                continue
            if key not in known:
                raise MatError("%s: preset %s sets `%s`, which no parameter binds "
                               "(known: %s)"
                               % (src, preset["name"], key, ", ".join(sorted(known))))

    # A parameter the fragment stage neither declares nor mentions is the drift
    # this whole format exists to stop. Vertex-stage ones are exempt: they are
    # declared in the hand-written .vs and are program-wide once linked.
    for p in mat["parameters"]:
        if p.get("stage") == "vertex":
            continue
        if not re.search(r"\b%s\b" % re.escape(p["uniform"]), fragment):
            raise MatError(
                "%s: `%s` is declared but the fragment block never reads it. "
                "Either use it, mark it `stage: vertex`, or delete it — a "
                "parameter nothing consumes is what produced the u_topY bug."
                % (src, p["uniform"]))
    return mat


def emit_glsl(mat):
    out = [BANNER_GLSL.format(src=mat["src"]), "#version 330"]
    for inc in mat["includes"]:
        out.append('#include "%s"' % inc)
    out.append("")
    for p in mat["parameters"]:
        if p.get("stage") == "vertex":
            continue  # declared in the hand-written .vs
        glsl = p.get("glsl", KINDS[p["kind"]][0])
        out.append("uniform %-9s %s;" % (glsl, p["uniform"]))
    out.append("")
    out.append(mat["fragment"].strip())
    out.append("")
    return "\n".join(out)


def emit_table(mat):
    rows = []
    for p in mat["parameters"]:
        macro = KINDS[p["kind"]][1]
        if macro is None:
            continue  # extern: the shader declares it, the table does not bind it
        if p["kind"] == "const":
            rows.append('    %s("%s", %s),' % (macro, p["uniform"], p["value"]))
        elif p["kind"] == "float" and any(k in p for k in ("a", "b", "lo", "hi")):
            rows.append('    P_AFFINE("%s", %s, %s, %s, %s, %s, %s),'
                        % (p["uniform"], mat["struct"], p["field"],
                           p.get("a", "0.0f"), p.get("b", "1.0f"),
                           p.get("lo", "-1e30f"), p.get("hi", "1e30f")))
        else:
            rows.append('    %s("%s", %s, %s),'
                        % (macro, p["uniform"], mat["struct"], p["field"]))
    out = ("#define %s_OUTPUT_SURFACE %s\n"
           "/* %s — %d parameters, output: %s */\n"
           "static const VfxParamDesc %s[] = {\n%s\n};\n"
           % (mat["table"], OUTPUT_SURFACE[mat["output"]], mat["src"],
              len(mat["parameters"]), mat["output"], mat["table"],
              "\n".join(rows)))

    if mat["presets"]:
        rows = []
        for preset in mat["presets"]:
            sets = ", ".join(".%s = %s" % (k, v) for k, v in preset.items()
                             if k not in ("name", "texture_path"))
            rows.append("    [%s] = { %s }," % (preset["name"], sets))
        out += ("\n/* Presets: authored parameter sets, indexed by the enum. */\n"
                "static const %s %s_PRESETS[] = {\n%s\n};\n"
                % (mat["struct"], mat["table"], "\n".join(rows)))
        tex = [p for p in mat["presets"] if p.get("texture_path")]
        if tex:
            rows = ['    [%s] = %s,' % (p["name"], p["texture_path"]) for p in tex]
            out += ("\n/* A preset's texture is LOADED, so it cannot live in the\n"
                    " * initializer above — it is a path resolved at Get() time. */\n"
                    "static const char *%s_PRESET_TEXTURES[] = {\n%s\n};\n"
                    % (mat["table"], "\n".join(rows)))

    defaults = [p for p in mat["parameters"] if p.get("default")]
    if defaults:
        rows = ['    { offsetof(%s, %s), %s },' % (mat["struct"], p["field"], p["default"])
                for p in defaults]
        out += ("\n/* Texture defaults: applied when the caller left the field at id 0. */\n"
                "static const VfxTextureDefault %s_DEFAULTS[] = {\n%s\n};\n"
                % (mat["table"], "\n".join(rows)))
    return out


def main():
    if not MAT_DIR.is_dir():
        print("gen_materials: no %s, nothing to do" % MAT_DIR.relative_to(ROOT))
        return 0

    sources = sorted(MAT_DIR.glob("*.mat"))
    if not sources:
        print("gen_materials: no .mat files, nothing to do")
        return 0

    tables = [BANNER_C]
    for path in sources:
        try:
            mat = parse_mat(path)
        except MatError as err:
            print("gen_materials: ERROR %s" % err, file=sys.stderr)
            return 1
        (SHADER_OUT_DIR / ("%s.fs" % mat["name"])).write_text(emit_glsl(mat))
        tables.append(emit_table(mat))
        print("gen_materials: %s -> core/shaders/%s.fs (%d params)"
              % (mat["src"], mat["name"], len(mat["parameters"])))

    TABLE_OUT.write_text("\n".join(tables))
    print("gen_materials: %d material(s) -> %s"
          % (len(sources), TABLE_OUT.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
