#!/usr/bin/env python3
"""Generate the C surface table from the canonical VFX asset manifest."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets" / "vfx_surface_profiles.json"
OUTPUT = ROOT / "core" / "vfx_surface_registry.generated.inl"

PRIMITIVES = {
    "ribbon": "VFX_SURFACE_PRIMITIVE_RIBBON",
    "tube": "VFX_SURFACE_PRIMITIVE_TUBE",
    "puff": "VFX_SURFACE_PRIMITIVE_PUFF",
    "fire_tongue": "VFX_SURFACE_PRIMITIVE_FIRE_TONGUE",
}
WRAPS = {"clamp": "VFX_SURFACE_WRAP_CLAMP", "repeat": "VFX_SURFACE_WRAP_REPEAT"}


def c_string(value):
    if value is None:
        return "NULL"
    return json.dumps(value)


def asset(profile, role, field):
    return profile.get("assets", {}).get(role, {}).get(field)


def main():
    profiles = json.loads(MANIFEST.read_text(encoding="utf-8"))["profiles"]
    lines = [
        "// GENERATED by scripts/gen_vfx_surface_registry.py from assets/vfx_surface_profiles.json.",
        "// Do not edit this file by hand.",
    ]
    for profile in profiles:
        columns, rows, frames = profile["flipbook"]
        lines.extend([
            f"    [{profile['id']}] = {{",
            f"        .id = {profile['id']},",
            f"        .primitive = {PRIMITIVES[profile['primitive']]},",
            f"        .wrap = {WRAPS[profile['wrap']]},",
            f"        .name = {c_string(profile['name'])},",
            f"        .bodyPath = {c_string(asset(profile, 'body', 'path'))},",
            f"        .flowPath = {c_string(asset(profile, 'flow', 'path'))},",
            f"        .maskPath = {c_string(asset(profile, 'mask', 'path'))},",
            f"        .fallbackBodyPath = {c_string(asset(profile, 'fallback_body', 'path'))},",
            f"        .bodyChannels = {c_string(asset(profile, 'body', 'channels'))},",
            f"        .flowChannels = {c_string(asset(profile, 'flow', 'channels'))},",
            f"        .maskChannels = {c_string(asset(profile, 'mask', 'channels'))},",
            f"        .seam = {c_string(profile['seam'])},",
            f"        .provenance = {c_string(profile['provenance'])},",
            f"        .flipbookColumns = {columns},",
            f"        .flipbookRows = {rows},",
            f"        .flipbookFrames = {frames},",
            "    },",
        ])
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
