#!/bin/bash
# Regenerates third_party/vulkan/rlvk_shaders.h from the embedded default shader sources.
# Requires glslc (Vulkan SDK, or the Android NDK's shader-tools copy).
#   GLSLC=/path/to/glslc ./scripts/gen_rlvk_shaders.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHADER_DIR="$ROOT/third_party/vulkan/shaders"
OUT="$ROOT/third_party/vulkan/rlvk_shaders.h"

GLSLC="${GLSLC:-glslc}"
if ! command -v "$GLSLC" >/dev/null 2>&1; then
    NDK_GLSLC=$(ls "$HOME"/Library/Android/sdk/ndk/*/shader-tools/darwin-x86_64/glslc 2>/dev/null | sort | tail -1)
    if [ -n "$NDK_GLSLC" ]; then GLSLC="$NDK_GLSLC"; else
        echo "glslc not found (set GLSLC=...)" >&2; exit 1
    fi
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Baseline is Vulkan 1.1 — never raise this: 1.1 SPIR-V (1.3) loads everywhere we ship.
"$GLSLC" --target-env=vulkan1.1 -O -o "$TMP/vert.spv" "$SHADER_DIR/rlvk_default.vert"
"$GLSLC" --target-env=vulkan1.1 -O -o "$TMP/frag.spv" "$SHADER_DIR/rlvk_default.frag"

emit_array() { # name, file
    python3 - "$1" "$2" <<'EOF'
import sys, struct
name, path = sys.argv[1], sys.argv[2]
data = open(path, "rb").read()
assert len(data) % 4 == 0
words = struct.unpack("<%dI" % (len(data)//4), data)
print("static const unsigned int %s[%d] = {" % (name, len(words)))
for i in range(0, len(words), 8):
    print("    " + ", ".join("0x%08x" % w for w in words[i:i+8]) + ",")
print("};")
EOF
}

{
    echo "// Auto-generated by scripts/gen_rlvk_shaders.sh — DO NOT EDIT."
    echo "// Embedded SPIR-V for rlvk's default shader (fallback when shaderc is absent)."
    echo "// Sources: third_party/vulkan/shaders/rlvk_default.vert/.frag (Vulkan 1.1 target)."
    echo "#ifndef RLVK_SHADERS_H"
    echo "#define RLVK_SHADERS_H"
    echo ""
    emit_array rlvkDefaultVertSpv "$TMP/vert.spv"
    echo ""
    emit_array rlvkDefaultFragSpv "$TMP/frag.spv"
    echo ""
    echo "#endif // RLVK_SHADERS_H"
} > "$OUT"

echo "Wrote $OUT"
