#!/usr/bin/env python3
"""Generate the decal-material descriptor table from its canonical JSON."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "core" / "decals" / "decal_materials.json"
OUTPUT = ROOT / "core" / "decals" / "decal_materials.generated.inl"
TINTS = {
    "body": "DECAL_TINT_BODY",
    "soft": "DECAL_TINT_SOFT",
    "white": "DECAL_TINT_WHITE",
}


def main():
    materials = json.loads(MANIFEST.read_text(encoding="utf-8"))["materials"]
    lines = [
        "// GENERATED by scripts/gen_decal_materials.py from core/decals/decal_materials.json.",
        "// Do not edit this file by hand.",
    ]
    for material in materials:
        lines.extend([
            f"    [{material['id']}] = {{",
            f"        .surface = {material['surface']},",
            f"        .tintPolicy = {TINTS[material['tint']]},",
            f"        .radiusBase = {material['radius_base']}f,",
            f"        .radiusSeverity = {material['radius_severity']}f,",
            f"        .lifetimeBase = {material['lifetime_base']}f,",
            f"        .lifetimeSeverity = {material['lifetime_severity']}f,",
            f"        .yOffset = {material['y_offset']}f,",
            f"        .alphaBase = {material['alpha_base']}f,",
            f"        .alphaSeverity = {material['alpha_severity']}f,",
            f"        .emissiveThreshold = {material['emissive_threshold']}f,",
            f"        .emissiveIntensity = {material['emissive_intensity']}f,",
            "    },",
        ])
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
