#!/usr/bin/env python3
"""Generate the C surface table from the canonical VFX asset manifest."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets" / "vfx_surface_profiles.json"
OUTPUT = ROOT / "core" / "vfx_surface_registry.generated.inl"

PRIMITIVES = {
    "ribbon": "VFX_SURFACE_PRIMITIVE_RIBBON",
    "tube": "VFX_SURFACE_PRIMITIVE_TUBE",
    "puff": "VFX_SURFACE_PRIMITIVE_PUFF",
    "fire_tongue": "VFX_SURFACE_PRIMITIVE_FIRE_TONGUE",
    "decal": "VFX_SURFACE_PRIMITIVE_DECAL",
    "disc": "VFX_SURFACE_PRIMITIVE_DISC",
}
WRAPS = {"clamp": "VFX_SURFACE_WRAP_CLAMP", "repeat": "VFX_SURFACE_WRAP_REPEAT"}
FILTERS = {"bilinear": "VFX_SURFACE_FILTER_BILINEAR", "point": "VFX_SURFACE_FILTER_POINT"}
BLENDS = {
    "consumer_defined": "VFX_SURFACE_BLEND_CONSUMER_DEFINED",
    "alpha": "VFX_SURFACE_BLEND_ALPHA",
    "additive": "VFX_SURFACE_BLEND_ADDITIVE",
    "multiplied": "VFX_SURFACE_BLEND_MULTIPLIED",
}
ROLES = {
    "trail": "VFX_SURFACE_ROLE_TRAIL",
    "residue": "VFX_SURFACE_ROLE_RESIDUE",
    "scorch": "VFX_SURFACE_ROLE_SCORCH",
    "impact": "VFX_SURFACE_ROLE_IMPACT",
    "rune": "VFX_SURFACE_ROLE_RUNE",
}


def c_string(value):
    if value is None:
        return "NULL"
    return json.dumps(value)


def asset(profile, role, field):
    return profile.get("assets", {}).get(role, {}).get(field)


def main():
    profiles = json.loads(MANIFEST.read_text(encoding="utf-8"))["profiles"]
    lines = [
        "// GENERATED by scripts/gen_vfx_surface_registry.py from assets/vfx_surface_profiles.json.",
        "// Do not edit this file by hand.",
    ]
    for profile in profiles:
        columns, rows, frames = profile["flipbook"]
        lines.extend([
            f"    [{profile['id']}] = {{",
        f"        .id = {profile['id']},",
        f"        .primitive = {PRIMITIVES[profile['primitive']]},",
        f"        .role = {ROLES[profile['role']]},",
        f"        .wrap = {WRAPS[profile['wrap']]},",
        f"        .filter = {FILTERS[profile['filter']]},",
        f"        .blend = {BLENDS[profile['blend']]},",
            f"        .name = {c_string(profile['name'])},",
            f"        .bodyPath = {c_string(asset(profile, 'body', 'path'))},",
            f"        .flowPath = {c_string(asset(profile, 'flow', 'path'))},",
        f"        .maskPath = {c_string(asset(profile, 'mask', 'path'))},",
        f"        .gradientPath = {c_string(asset(profile, 'gradient', 'path'))},",
            f"        .fallbackBodyPath = {c_string(asset(profile, 'fallback_body', 'path'))},",
            f"        .bodyChannels = {c_string(asset(profile, 'body', 'channels'))},",
            f"        .flowChannels = {c_string(asset(profile, 'flow', 'channels'))},",
        f"        .maskChannels = {c_string(asset(profile, 'mask', 'channels'))},",
        f"        .gradientChannels = {c_string(asset(profile, 'gradient', 'channels'))},",
        f"        .seam = {c_string(profile['seam'])},",
        f"        .projection = {c_string(profile['projection'])},",
        f"        .provenance = {c_string(profile['provenance'])},",
        f"        .approval = {c_string(profile['approval'])},",
        f"        .lifetimeSeconds = {profile['lifecycle']['seconds']}f,",
        f"        .fadeInSeconds = {profile['lifecycle']['fade_in']}f,",
        f"        .fadeOutSeconds = {profile['lifecycle']['fade_out']}f,",
        f"        .maxSlopeDegrees = {profile.get('max_slope_degrees', 90.0)}f,",
        f"        .maxDrawCalls = {profile['budget']['max_draw_calls']},",
        f"        .maxTextures = {profile['budget']['max_textures']},",
            f"        .flipbookColumns = {columns},",
            f"        .flipbookRows = {rows},",
            f"        .flipbookFrames = {frames},",
            "    },",
        ])
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
