#!/usr/bin/env python3
"""Generate the OPAQUE-layout surface sheets scrolled over a deformed volume.

One script, a family of sheets: smoke / fire / steam. They differ in parameters,
not in code, because the thing that makes them different is authoring intent and
that belongs in a table.

CHANNEL CONTRACT — assets/TEXTURE_PACKING.md, layout OPAQUE, every channel TILE:

    R = G = B = smoke luminance   (GREY, so the consumer's tint survives)
    A                 = coverage  (real opacity, eroded so the body breaks up)

THE LAYOUT IS THE WHOLE POINT, AND THE FIRST VERSION GOT IT WRONG. These sheets
are consumed by core/trails/shaders/trail_body.fs, which does
`sheet.rgb * fragColor.rgb` and `alpha = sheet.a` — an ordinary COLOUR read. The
first version shipped them as layout STRAND, whose R/G/B are three unrelated
noise FIELDS and whose A is a dissolve mask. Sampled as colour that is exactly
what it looks like: rainbow mush at an arbitrary opacity. TEXTURE_PACKING.md R4
says so in as many words — "in STRAND and FLOW, A is DATA, not coverage" — and
the spec was written before the sheet was.

Grey rather than coloured RGB is deliberate: the tint comes from VFX_Material at
the call site, so any colour baked here would multiply against it and fight it.

READ THIS BEFORE CHANGING ANYTHING HERE.

WHY EVERY CHANNEL TILES, unlike smoke_strand.png. That sheet is a SHAPE: R and G
are one complete wisp each with head and tail taper painted in, so it is
stretched once over a trail. These sheets are a MATERIAL wrapped around a
volume: the body is generated by geometry (core/deform churns the section) and
the sheet only supplies surface detail, which must repeat as the body grows and
must not carry a silhouette of its own. Tiling a shape sheet gives a rope;
stretching a material sheet gives a smear. The two are not interchangeable and
the layout string in the manifest is what records which is which.

WHY SEAMLESS ON BOTH AXES IS NON-NEGOTIABLE. The section is closed: u = 0 and
u = 1 are the same line on the cylinder. A field that is not periodic leaves a
visible crease running the entire length of the body. Seamlessness here is by
CONSTRUCTION, not by cross-fading: every component is a harmonic with integer
frequency in both axes, so the value at u = 0 equals the value at u = 1 by
definition. Cross-fading a seam blurs the detail near it and, for a signed
field, averages opposing values into nothing.

Uses only the Python standard library.
"""

from __future__ import annotations

import math
import random
import struct
import zlib
from pathlib import Path

SIZE = 256
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "assets" / "textures"
TAU = math.tau


# --- PNG ---------------------------------------------------------------------

def write_png(path: Path, pixels: bytes, width: int, height: int) -> None:
    raw = bytearray()
    stride = width * 4
    for y in range(height):
        raw.append(0)  # filter type 0
        raw.extend(pixels[y * stride:(y + 1) * stride])

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data +
                struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    path.write_bytes(b"\x89PNG\r\n\x1a\n" +
                     chunk(b"IHDR", header) +
                     chunk(b"IDAT", zlib.compress(bytes(raw), 9)) +
                     chunk(b"IEND", b""))


# --- Periodic field ----------------------------------------------------------

def make_modes(rng: random.Random, count: int, max_freq: int) -> list:
    """Harmonics with INTEGER frequency in both axes — the seamlessness."""
    modes = []
    for _ in range(count):
        ku = rng.randint(1, max_freq)
        kv = rng.randint(1, max_freq)
        modes.append((ku, kv, rng.uniform(0.0, TAU), 1.0 / (ku + kv)))
    return modes


def sample(modes: list, u: float, v: float) -> float:
    total = 0.0
    weight = 0.0
    for ku, kv, phase, amp in modes:
        total += amp * math.sin(TAU * (ku * u + kv * v) + phase)
        weight += amp
    return 0.5 + 0.5 * (total / weight if weight > 0.0 else 0.0)


def billow(modes: list, u: float, v: float) -> float:
    """Ridged/billowed variant — smoke reads as lumps, not as a sine field."""
    return 1.0 - abs(2.0 * sample(modes, u, v) - 1.0)


# --- The family --------------------------------------------------------------
# Only these numbers differ between the three sheets.
PROFILES = {
    "smoke": dict(seed=20260803, coarse=5, fine=13, detail=17,
                  coarse_gain=1.00, fine_gain=0.85, contrast=1.15,
                  distort=1.0, note="soft rolling billows"),
    "fire":  dict(seed=20260804, coarse=7, fine=19, detail=23,
                  coarse_gain=1.15, fine_gain=1.05, contrast=1.55,
                  distort=1.35, note="tighter, higher contrast tongues"),
    "steam": dict(seed=20260805, coarse=3, fine=9, detail=11,
                  coarse_gain=0.85, fine_gain=0.60, contrast=0.80,
                  distort=0.7, note="wide, low-contrast, almost translucent"),
}


def build(name: str, cfg: dict) -> None:
    rng = random.Random(cfg["seed"])
    coarse = make_modes(rng, 14, cfg["coarse"])
    fine = make_modes(rng, 20, cfg["fine"])
    dist_u = make_modes(rng, 10, cfg["coarse"])
    detail = make_modes(rng, 24, cfg["detail"])

    px = bytearray(SIZE * SIZE * 4)
    for y in range(SIZE):
        v = y / SIZE
        for x in range(SIZE):
            u = x / SIZE

            # NOTHING may scale u or v here. The seamlessness comes from every
            # component having an INTEGER frequency in both axes, and u * 1.7 is
            # not periodic with period 1 — it lands at 1.7 where it started at
            # 0, and the wrap develops a crease. (It did: the wrap/interior
            # instrument below read 3.4x before this was fixed.) Channels are
            # differentiated by their FREQUENCY RANGE instead, which keeps every
            # harmonic integer.
            # LUMINANCE — two octaves of billow, combined into ONE grey value.
            # Smoke is lit matter, not three independent fields.
            lum = billow(coarse, u, v) * cfg["coarse_gain"] * 0.65 \
                + billow(fine, u, v) * cfg["fine_gain"] * 0.35
            lum = min(1.0, max(0.0, (lum - 0.5) * cfg["contrast"] + 0.55))
            r = g = b = lum

            # COVERAGE — the silhouette's detail. Multiplied by the luminance so
            # thin wisps are both dimmer AND more transparent, which is what
            # stops the sheet reading as a printed pattern on a solid tube. A
            # gamma above 1 keeps most of it fairly open, or the volume closes
            # into a painted cylinder.
            cov = sample(detail, u, v) * (0.45 + 0.55 * lum)
            a = min(1.0, max(0.0, cov)) ** 1.35

            i = (y * SIZE + x) * 4
            px[i + 0] = int(r * 255.0 + 0.5)
            px[i + 1] = int(g * 255.0 + 0.5)
            px[i + 2] = int(b * 255.0 + 0.5)
            px[i + 3] = int(a * 255.0 + 0.5)

    out = OUT_DIR / f"volume_surface_{name}.png"
    write_png(out, bytes(px), SIZE, SIZE)

    # Measure the seam rather than asserting it — but measure the RIGHT thing.
    #
    # Column 0 and column SIZE-1 are ADJACENT across the wrap, not duplicates of
    # each other, so their difference should not be zero: it should be an
    # ordinary neighbour step. Comparing them for equality is the instrument
    # error, and it reports a healthy tiling texture as broken.
    #
    # The honest test is the wrap step against the texture's OWN local variation.
    # A ratio near 1 means the wrap looks like any other column boundary, which
    # is what seamless means. A ratio of several means there is a visible crease.
    def mean_step(a_col: int, b_col: int) -> float:
        total = 0
        for y in range(SIZE):
            for c in range(4):
                total += abs(px[(y * SIZE + a_col) * 4 + c] -
                             px[(y * SIZE + b_col) * 4 + c])
        return total / (SIZE * 4)

    wrap = mean_step(SIZE - 1, 0)
    interior = sum(mean_step(x, x + 1) for x in range(0, SIZE - 1, 8))
    interior /= len(range(0, SIZE - 1, 8))
    ratio = wrap / interior if interior > 0.0 else 0.0
    verdict = "seamless" if ratio < 1.5 else "CREASE"
    print(f"  {out.name:32s} {cfg['note']:38s} "
          f"wrap/interior = {ratio:.2f}  {verdict}")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"volume surface sheets ({SIZE}x{SIZE}, OPAQUE layout, all channels TILE):")
    for name, cfg in PROFILES.items():
        build(name, cfg)
    print("\nRegistered in assets/vfx_surface_profiles.json; run "
          "scripts/gen_vfx_surface_registry.py after changing that file.")


if __name__ == "__main__":
    main()
