import os
import re

LEGACY_HEADERS = {
    "fluid_skill.h", "tube_skill.h", "metal_skill.h", "fire_skill.h",
    "wood_skill.h", "electric_skill.h", "wind_skill.h", "shield_skill.h"
}

ELEMENT_COLORS = {
    "water": "ELEMENT_COLOR_WATER",
    "fire": "ELEMENT_COLOR_FIRE",
    "metal": "ELEMENT_COLOR_METAL",
    "wood": "ELEMENT_COLOR_WOOD",
    "earth": "ELEMENT_COLOR_EARTH",
    "taiji": "ELEMENT_COLOR_TAIJI"
}

def to_upper_snake(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    skills_dir = os.path.join(root_dir, "skills")
    
    # 1. Kiểm tra sự hiện diện của các thư mục kỹ năng mặc định (legacy)
    legacy_skills = {
        "HAS_SKILL_FLUID": os.path.exists(os.path.join(skills_dir, "water", "water_projectile")),
        "HAS_SKILL_TUBE": os.path.exists(os.path.join(skills_dir, "water", "water_stream")),
        "HAS_SKILL_SHIELD": os.path.exists(os.path.join(skills_dir, "water", "water_shield")),
        "HAS_SKILL_METAL": os.path.exists(os.path.join(skills_dir, "metal", "metal_projectile")),
        "HAS_SKILL_FIRE": os.path.exists(os.path.join(skills_dir, "fire", "fire_ball")),
        "HAS_SKILL_WOOD": os.path.exists(os.path.join(skills_dir, "wood", "wood_roots")),
        "HAS_SKILL_ELECTRIC": os.path.exists(os.path.join(skills_dir, "taiji", "lightning")),
        "HAS_SKILL_WIND": os.path.exists(os.path.join(skills_dir, "taiji", "wind_storm")),
    }
    
    # Sinh file cấu hình core/skills_config.h
    config_path = os.path.join(root_dir, "core", "skills_config.h")
    with open(config_path, "w", encoding="utf-8") as cfg:
        cfg.write("// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_REGISTRY.PY - DO NOT MODIFY\n")
        cfg.write("#ifndef SKILLS_CONFIG_H\n")
        cfg.write("#define SKILLS_CONFIG_H\n\n")
        for macro, exists in legacy_skills.items():
            value = 1 if exists else 0
            cfg.write(f"#define {macro} {value}\n")
        cfg.write("\n#endif // SKILLS_CONFIG_H\n")
        
    # 2. Quét các kỹ năng custom mới tạo thêm
    generated_skills = []
    if os.path.exists(skills_dir):
        for dirpath, _, filenames in os.walk(skills_dir):
            for f in filenames:
                if f.endswith(".h") and f not in LEGACY_HEADERS and f != "sword_rain_skill.h":
                    header_path = os.path.join(dirpath, f)
                    with open(header_path, "r", encoding="utf-8", errors="ignore") as fh:
                        content = fh.read()
                        
                    match = re.search(r"void\s+Init([A-Za-z0-9_]+)Skill\s*\(\s*int", content)
                    if match:
                        prefix = match.group(1)
                        if (f"Cast{prefix}Skill" in content and 
                            f"Update{prefix}Skill" in content and 
                            f"Unload{prefix}Skill" in content):
                            
                            rel_path = os.path.relpath(header_path, root_dir)
                            
                            element = "default"
                            parts = rel_path.split(os.sep)
                            if len(parts) > 1:
                                element = parts[1]
                            color = ELEMENT_COLORS.get(element.lower(), "WHITE")
                            
                            display_name = to_upper_snake(prefix)
                            
                            generated_skills.append({
                                "prefix": prefix,
                                "include": rel_path,
                                "name": display_name,
                                "color": color
                            })
                        
    # Sinh file header C đăng ký kỹ năng
    gen_path = os.path.join(root_dir, "core", "skills_generated.h")
    with open(gen_path, "w", encoding="utf-8") as out:
        out.write("// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_REGISTRY.PY - DO NOT MODIFY MANUAL\n")
        out.write("#ifndef SKILLS_GENERATED_H\n")
        out.write("#define SKILLS_GENERATED_H\n\n")
        out.write('#include "core/skill_manager.h"\n\n')
        
        for s in generated_skills:
            out.write(f'#include "{s["include"]}"\n')
        out.write("\n")
        
        out.write("static inline void RegisterGeneratedSkills(void) {\n")
        for s in generated_skills:
            out.write(f'    RegisterSkill("{s["name"]}", {s["color"]}, Init{s["prefix"]}Skill, Cast{s["prefix"]}Skill, Update{s["prefix"]}Skill, Draw{s["prefix"]}Skill, Unload{s["prefix"]}Skill);\n')
        out.write("}\n\n")
        out.write("#endif // SKILLS_GENERATED_H\n")
        
    print(f"Generated config and registry.")

if __name__ == "__main__":
    main()
