import os
import re

LEGACY_HEADERS = {
    "fluid_skill.h", "tube_skill.h", "metal_skill.h", "fire_skill.h",
    "wood_skill.h", "electric_skill.h", "wind_skill.h", "shield_skill.h"
}

ELEMENT_COLORS = {
    "water": "SKYBLUE",
    "fire": "ORANGE",
    "metal": "GOLD",
    "wood": "LIME",
    "earth": "BROWN",
    "taiji": "PURPLE"
}

def to_upper_snake(name):
    # Thêm gạch dưới trước các chữ in hoa và viết hoa toàn bộ
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    skills_dir = os.path.join(root_dir, "skills")
    
    generated_skills = []
    
    for dirpath, _, filenames in os.walk(skills_dir):
        for f in filenames:
            if f.endswith(".h") and f not in LEGACY_HEADERS:
                header_path = os.path.join(dirpath, f)
                with open(header_path, "r", encoding="utf-8", errors="ignore") as fh:
                    content = fh.read()
                    
                # Quét xem có đúng chuẩn thiết kế lifecycle Init/Cast/Update/Unload hay không
                match = re.search(r"void\s+Init([A-Za-z0-9_]+)Skill\s*\(\s*int", content)
                if match:
                    prefix = match.group(1)
                    # Xác thực sự hiện diện đầy đủ của các hàm còn lại
                    if (f"Cast{prefix}Skill" in content and 
                        f"Update{prefix}Skill" in content and 
                        f"Unload{prefix}Skill" in content):
                        
                        rel_path = os.path.relpath(header_path, root_dir)
                        
                        # Xác định màu sắc dựa trên thư mục nguyên tố
                        element = "default"
                        parts = rel_path.split(os.sep)
                        if len(parts) > 1:
                            element = parts[1] # e.g. "earth" từ skills/earth/earth_rock
                        color = ELEMENT_COLORS.get(element.lower(), "WHITE")
                        
                        display_name = to_upper_snake(prefix)
                        
                        generated_skills.append({
                            "prefix": prefix,
                            "include": rel_path,
                            "name": display_name,
                            "color": color
                        })
                        
    # Sinh file header C
    gen_path = os.path.join(root_dir, "core", "skills_generated.h")
    
    with open(gen_path, "w", encoding="utf-8") as out:
        out.write("// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_REGISTRY.PY - DO NOT MODIFY MANUAL\n")
        out.write("#ifndef SKILLS_GENERATED_H\n")
        out.write("#define SKILLS_GENERATED_H\n\n")
        out.write('#include "core/skill_manager.h"\n\n')
        
        # Viết các lệnh include
        for s in generated_skills:
            out.write(f'#include "{s["include"]}"\n')
        out.write("\n")
        
        # Viết hàm đăng ký tự động
        out.write("static inline void RegisterGeneratedSkills(void) {\n")
        for s in generated_skills:
            # Check xem Draw[Prefix]Skill có khai báo hay không, nếu không mặc định truyền NULL
            # Mặc định chúng ta có thể truyền Draw[Prefix]Skill trực tiếp vì template chuẩn có khai báo hàm này
            out.write(f'    RegisterSkill("{s["name"]}", {s["color"]}, Init{s["prefix"]}Skill, Cast{s["prefix"]}Skill, Update{s["prefix"]}Skill, Draw{s["prefix"]}Skill, Unload{s["prefix"]}Skill);\n')
        out.write("}\n\n")
        out.write("#endif // SKILLS_GENERATED_H\n")
        
    print(f"Generated registry at {gen_path} with {len(generated_skills)} skills.")

if __name__ == "__main__":
    main()
