import os
import re

def to_upper_snake(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    maps_dir = os.path.join(root_dir, "maps")
    
    generated_maps = []
    if os.path.exists(maps_dir):
        for dirpath, _, filenames in os.walk(maps_dir):
            for f in filenames:
                if f.endswith(".h"):
                    header_path = os.path.join(dirpath, f)
                    with open(header_path, "r", encoding="utf-8", errors="ignore") as fh:
                        content = fh.read()
                        
                    match = re.search(r"void\s+Init([A-Za-z0-9_]+)Map\s*\(\s*void\)", content)
                    if match:
                        prefix = match.group(1)
                        if (f"Draw{prefix}Map" in content):
                            rel_path = os.path.relpath(header_path, root_dir)
                            display_name = to_upper_snake(prefix)
                            
                            has_update = f"Update{prefix}Map" in content
                            has_unload = f"Unload{prefix}Map" in content
                            
                            generated_maps.append({
                                "prefix": prefix,
                                "include": rel_path,
                                "name": display_name,
                                "has_update": has_update,
                                "has_unload": has_unload
                            })
                            
    gen_path = os.path.join(root_dir, "core", "maps_generated.h")
    with open(gen_path, "w", encoding="utf-8") as out:
        out.write("// AUTOMATICALLY GENERATED BY SCRIPTS/GENERATE_MAP_REGISTRY.PY - DO NOT MODIFY MANUAL\n")
        out.write("#ifndef MAPS_GENERATED_H\n")
        out.write("#define MAPS_GENERATED_H\n\n")
        out.write('#include "core/map_manager.h"\n\n')
        
        for m in generated_maps:
            out.write(f'#include "{m["include"]}"\n')
        out.write("\n")
        
        out.write("static inline void RegisterGeneratedMaps(void) {\n")
        for m in generated_maps:
            update_fn = f"Update{m['prefix']}Map" if m["has_update"] else "NULL"
            unload_fn = f"Unload{m['prefix']}Map" if m["has_unload"] else "NULL"
            out.write(f'    MapManager_Register("{m["name"]}", Init{m["prefix"]}Map, {update_fn}, Draw{m["prefix"]}Map, {unload_fn});\n')
        out.write("}\n\n")
        out.write("#endif // MAPS_GENERATED_H\n")
        
    print("Generated map registry.")

if __name__ == "__main__":
    main()
